# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict

AuthMode: TypeAlias = Literal["apikey", "chatgpt", "chatgptAuthTokens"]

PlanType: TypeAlias = Literal["free", "go", "plus", "pro", "team", "self_serve_business_usage_based", "business", "enterprise_cbp_usage_based", "enterprise", "edu", "unknown"]

class AccountUpdatedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    authMode: AuthMode | None = None
    planType: PlanType | None = None
