# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class CreditsSnapshot(BaseModel):
    model_config = ConfigDict(extra="allow")

    balance: str | None = None
    hasCredits: bool
    unlimited: bool

class RateLimitSnapshot(BaseModel):
    model_config = ConfigDict(extra="allow")

    credits: CreditsSnapshot | None = None
    limitId: str | None = None
    limitName: str | None = None
    planType: PlanType | None = None
    primary: RateLimitWindow | None = None
    secondary: RateLimitWindow | None = None

class RateLimitWindow(BaseModel):
    model_config = ConfigDict(extra="allow")

    resetsAt: int | None = None
    usedPercent: int
    windowDurationMins: int | None = None

PlanType: TypeAlias = Literal["free", "go", "plus", "pro", "team", "self_serve_business_usage_based", "business", "enterprise_cbp_usage_based", "enterprise", "edu", "unknown"]

class AccountRateLimitsUpdatedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    rateLimits: RateLimitSnapshot
