# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict


class AppBranding(BaseModel):
    """EXPERIMENTAL - app metadata returned by app-list APIs."""
    model_config = ConfigDict(extra="allow")

    category: str | None = None
    developer: str | None = None
    isDiscoverableApp: bool
    privacyPolicy: str | None = None
    termsOfService: str | None = None
    website: str | None = None

class AppInfo(BaseModel):
    """EXPERIMENTAL - app metadata returned by app-list APIs."""
    model_config = ConfigDict(extra="allow")

    appMetadata: AppMetadata | None = None
    branding: AppBranding | None = None
    description: str | None = None
    distributionChannel: str | None = None
    id: str
    installUrl: str | None = None
    isAccessible: bool = False
    isEnabled: bool = True
    labels: dict[str, Any] | None = None
    logoUrl: str | None = None
    logoUrlDark: str | None = None
    name: str
    pluginDisplayNames: list[str] = []

class AppMetadata(BaseModel):
    model_config = ConfigDict(extra="allow")

    categories: list[Any] | None = None
    developer: str | None = None
    firstPartyRequiresInstall: bool | None = None
    firstPartyType: str | None = None
    review: AppReview | None = None
    screenshots: list[Any] | None = None
    seoDescription: str | None = None
    showInComposerWhenUnlinked: bool | None = None
    subCategories: list[Any] | None = None
    version: str | None = None
    versionId: str | None = None
    versionNotes: str | None = None

class AppReview(BaseModel):
    model_config = ConfigDict(extra="allow")

    status: str

class AppScreenshot(BaseModel):
    model_config = ConfigDict(extra="allow")

    fileId: str | None = None
    url: str | None = None
    userPrompt: str

class AppListUpdatedNotification(BaseModel):
    """EXPERIMENTAL - notification emitted when the app list changes."""
    model_config = ConfigDict(extra="allow")

    data: list[AppInfo]
