# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class CommandExecTerminalSize(BaseModel):
    """PTY size in character cells for `command/exec` PTY sessions."""
    model_config = ConfigDict(extra="allow")

    cols: int
    rows: int

class RestrictedReadOnlyAccess(BaseModel):
    model_config = ConfigDict(extra="allow")

    includePlatformDefaults: bool = True
    readableRoots: list[AbsolutePathBuf] = []
    type: Literal["restricted"]

class FullAccessReadOnlyAccess(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["fullAccess"]

class DangerFullAccessSandboxPolicy(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["dangerFullAccess"]

class ReadOnlySandboxPolicy(BaseModel):
    model_config = ConfigDict(extra="allow")

    access: ReadOnlyAccess = {"type": "fullAccess"}
    networkAccess: bool = False
    type: Literal["readOnly"]

class ExternalSandboxSandboxPolicy(BaseModel):
    model_config = ConfigDict(extra="allow")

    networkAccess: NetworkAccess = "restricted"
    type: Literal["externalSandbox"]

class WorkspaceWriteSandboxPolicy(BaseModel):
    model_config = ConfigDict(extra="allow")

    excludeSlashTmp: bool = False
    excludeTmpdirEnvVar: bool = False
    networkAccess: bool = False
    readOnlyAccess: ReadOnlyAccess = {"type": "fullAccess"}
    type: Literal["workspaceWrite"]
    writableRoots: list[AbsolutePathBuf] = []

AbsolutePathBuf: TypeAlias = str

NetworkAccess: TypeAlias = Literal["restricted", "enabled"]

ReadOnlyAccess: TypeAlias = RestrictedReadOnlyAccess | FullAccessReadOnlyAccess

SandboxPolicy: TypeAlias = DangerFullAccessSandboxPolicy | ReadOnlySandboxPolicy | ExternalSandboxSandboxPolicy | WorkspaceWriteSandboxPolicy

class CommandExecParams(BaseModel):
    """Run a standalone command (argv vector) in the server sandbox without creating a thread or turn.

The final `command/exec` response is deferred until the process exits and is sent only after all `command/exec/outputDelta` notifications for that connection have been emitted."""
    model_config = ConfigDict(extra="allow")

    command: list[str]
    cwd: str | None = None
    disableOutputCap: bool | None = None
    disableTimeout: bool | None = None
    env: dict[str, Any] | None = None
    outputBytesCap: int | None = None
    processId: str | None = None
    sandboxPolicy: SandboxPolicy | None = None
    size: CommandExecTerminalSize | None = None
    streamStdin: bool | None = None
    streamStdoutStderr: bool | None = None
    timeoutMs: int | None = None
    tty: bool | None = None
