# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict

CommandExecOutputStream: TypeAlias = Literal["stdout", "stderr"]

class CommandExecOutputDeltaNotification(BaseModel):
    """Base64-encoded output chunk emitted for a streaming `command/exec` request.

These notifications are connection-scoped. If the originating connection closes, the server terminates the process."""
    model_config = ConfigDict(extra="allow")

    capReached: bool
    deltaBase64: str
    processId: str
    stream: CommandExecOutputStream
