# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class CommandExecTerminateParams(BaseModel):
    """Terminate a running `command/exec` session."""
    model_config = ConfigDict(extra="allow")

    processId: str
