# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class CommandExecWriteParams(BaseModel):
    """Write stdin bytes to a running `command/exec` session, close stdin, or both."""
    model_config = ConfigDict(extra="allow")

    closeStdin: bool | None = None
    deltaBase64: str | None = None
    processId: str
