# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class TextPosition(BaseModel):
    model_config = ConfigDict(extra="allow")

    column: int
    line: int

class TextRange(BaseModel):
    model_config = ConfigDict(extra="allow")

    end: TextPosition
    start: TextPosition

class ConfigWarningNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    details: str | None = None
    path: str | None = None
    range: TextRange | None = None
    summary: str
