# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class ConfigLayerMetadata(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: ConfigLayerSource
    version: str

class OverriddenMetadata(BaseModel):
    model_config = ConfigDict(extra="allow")

    effectiveValue: Any
    message: str
    overridingLayer: ConfigLayerMetadata

class MdmConfigLayerSource(BaseModel):
    """Managed preferences layer delivered by MDM (macOS only)."""
    model_config = ConfigDict(extra="allow")

    domain: str
    key: str
    type: Literal["mdm"]

class SystemConfigLayerSource(BaseModel):
    """Managed config layer from a file (usually `managed_config.toml`)."""
    model_config = ConfigDict(extra="allow")

    file: AbsolutePathBuf
    type: Literal["system"]

class UserConfigLayerSource(BaseModel):
    """User config layer from $CODEX_HOME/config.toml. This layer is special in that it is expected to be: - writable by the user - generally outside the workspace directory"""
    model_config = ConfigDict(extra="allow")

    file: AbsolutePathBuf
    type: Literal["user"]

class ProjectConfigLayerSource(BaseModel):
    """Path to a .codex/ folder within a project. There could be multiple of these between `cwd` and the project/repo root."""
    model_config = ConfigDict(extra="allow")

    dotCodexFolder: AbsolutePathBuf
    type: Literal["project"]

class SessionFlagsConfigLayerSource(BaseModel):
    """Session-layer overrides supplied via `-c`/`--config`."""
    model_config = ConfigDict(extra="allow")

    type: Literal["sessionFlags"]

class LegacyManagedConfigTomlFromFileConfigLayerSource(BaseModel):
    """`managed_config.toml` was designed to be a config that was loaded as the last layer on top of everything else. This scheme did not quite work out as intended, but we keep this variant as a "best effort" while we phase out `managed_config.toml` in favor of `requirements.toml`."""
    model_config = ConfigDict(extra="allow")

    file: AbsolutePathBuf
    type: Literal["legacyManagedConfigTomlFromFile"]

class LegacyManagedConfigTomlFromMdmConfigLayerSource(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["legacyManagedConfigTomlFromMdm"]

AbsolutePathBuf: TypeAlias = str

ConfigLayerSource: TypeAlias = MdmConfigLayerSource | SystemConfigLayerSource | UserConfigLayerSource | ProjectConfigLayerSource | SessionFlagsConfigLayerSource | LegacyManagedConfigTomlFromFileConfigLayerSource | LegacyManagedConfigTomlFromMdmConfigLayerSource

WriteStatus: TypeAlias = Literal["ok", "okOverridden"]

class ConfigWriteResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    filePath: AbsolutePathBuf
    overriddenMetadata: OverriddenMetadata | None = None
    status: WriteStatus
    version: str
