# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class ConfigRequirements(BaseModel):
    model_config = ConfigDict(extra="allow")

    allowedApprovalPolicies: list[Any] | None = None
    allowedSandboxModes: list[Any] | None = None
    allowedWebSearchModes: list[Any] | None = None
    enforceResidency: ResidencyRequirement | None = None
    featureRequirements: dict[str, Any] | None = None

class NetworkRequirements(BaseModel):
    model_config = ConfigDict(extra="allow")

    allowLocalBinding: bool | None = None
    allowUnixSockets: list[Any] | None = None
    allowUpstreamProxy: bool | None = None
    allowedDomains: list[Any] | None = None
    dangerouslyAllowAllUnixSockets: bool | None = None
    dangerouslyAllowNonLoopbackProxy: bool | None = None
    deniedDomains: list[Any] | None = None
    domains: dict[str, Any] | None = None
    enabled: bool | None = None
    httpPort: int | None = None
    managedAllowedDomainsOnly: bool | None = None
    socksPort: int | None = None
    unixSockets: dict[str, Any] | None = None

class GranularAskForApproval(BaseModel):
    model_config = ConfigDict(extra="forbid")

    granular: GranularAskForApprovalGranular

class GranularAskForApprovalGranular(BaseModel):
    model_config = ConfigDict(extra="allow")

    mcp_elicitations: bool
    request_permissions: bool = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool = False

AskForApproval: TypeAlias = Literal["untrusted", "on-failure", "on-request", "never"] | GranularAskForApproval

NetworkDomainPermission: TypeAlias = Literal["allow", "deny"]

NetworkUnixSocketPermission: TypeAlias = Literal["allow", "none"]

ResidencyRequirement: TypeAlias = Literal["us"]

SandboxMode: TypeAlias = Literal["read-only", "workspace-write", "danger-full-access"]

WebSearchMode: TypeAlias = Literal["disabled", "cached", "live"]

class ConfigRequirementsReadResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    requirements: ConfigRequirements | None = None
