# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict, Field


class AnalyticsConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    enabled: bool | None = None

class AppConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    default_tools_approval_mode: AppToolApproval | None = None
    default_tools_enabled: bool | None = None
    destructive_enabled: bool | None = None
    enabled: bool = True
    open_world_enabled: bool | None = None
    tools: AppToolsConfig | None = None

class AppToolConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    approval_mode: AppToolApproval | None = None
    enabled: bool | None = None

class AppsConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    default: AppsDefaultConfig | None = Field(default=None, alias="_default")

class AppsDefaultConfig(BaseModel):
    model_config = ConfigDict(extra="allow")

    destructive_enabled: bool = True
    enabled: bool = True
    open_world_enabled: bool = True

class Config(BaseModel):
    model_config = ConfigDict(extra="allow")

    analytics: AnalyticsConfig | None = None
    approval_policy: AskForApproval | None = None
    approvals_reviewer: ApprovalsReviewer | None = None
    web_search: WebSearchMode | None = None
    compact_prompt: str | None = None
    developer_instructions: str | None = None
    forced_chatgpt_workspace_id: str | None = None
    forced_login_method: ForcedLoginMethod | None = None
    instructions: str | None = None
    model: str | None = None
    model_auto_compact_token_limit: int | None = None
    model_context_window: int | None = None
    model_provider: str | None = None
    model_reasoning_effort: ReasoningEffort | None = None
    model_reasoning_summary: ReasoningSummary | None = None
    model_verbosity: Verbosity | None = None
    profile: str | None = None
    profiles: dict[str, ProfileV2] = {}
    review_model: str | None = None
    sandbox_mode: SandboxMode | None = None
    sandbox_workspace_write: SandboxWorkspaceWrite | None = None
    service_tier: ServiceTier | None = None
    tools: ToolsV2 | None = None

class ConfigLayer(BaseModel):
    model_config = ConfigDict(extra="allow")

    config: Any
    disabledReason: str | None = None
    name: ConfigLayerSource
    version: str

class ConfigLayerMetadata(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: ConfigLayerSource
    version: str

class ProfileV2(BaseModel):
    model_config = ConfigDict(extra="allow")

    approval_policy: AskForApproval | None = None
    approvals_reviewer: ApprovalsReviewer | None = None
    chatgpt_base_url: str | None = None
    model: str | None = None
    model_provider: str | None = None
    model_reasoning_effort: ReasoningEffort | None = None
    model_reasoning_summary: ReasoningSummary | None = None
    model_verbosity: Verbosity | None = None
    service_tier: ServiceTier | None = None
    tools: ToolsV2 | None = None
    web_search: WebSearchMode | None = None

class SandboxWorkspaceWrite(BaseModel):
    model_config = ConfigDict(extra="allow")

    exclude_slash_tmp: bool = False
    exclude_tmpdir_env_var: bool = False
    network_access: bool = False
    writable_roots: list[str] = []

class ToolsV2(BaseModel):
    model_config = ConfigDict(extra="allow")

    view_image: bool | None = None
    web_search: WebSearchToolConfig | None = None

class WebSearchLocation(BaseModel):
    model_config = ConfigDict(extra="forbid")

    city: str | None = None
    country: str | None = None
    region: str | None = None
    timezone: str | None = None

class WebSearchToolConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    allowed_domains: list[Any] | None = None
    context_size: WebSearchContextSize | None = None
    location: WebSearchLocation | None = None

class GranularAskForApproval(BaseModel):
    model_config = ConfigDict(extra="forbid")

    granular: GranularAskForApprovalGranular

class MdmConfigLayerSource(BaseModel):
    """Managed preferences layer delivered by MDM (macOS only)."""
    model_config = ConfigDict(extra="allow")

    domain: str
    key: str
    type: Literal["mdm"]

class SystemConfigLayerSource(BaseModel):
    """Managed config layer from a file (usually `managed_config.toml`)."""
    model_config = ConfigDict(extra="allow")

    file: AbsolutePathBuf
    type: Literal["system"]

class UserConfigLayerSource(BaseModel):
    """User config layer from $CODEX_HOME/config.toml. This layer is special in that it is expected to be: - writable by the user - generally outside the workspace directory"""
    model_config = ConfigDict(extra="allow")

    file: AbsolutePathBuf
    type: Literal["user"]

class ProjectConfigLayerSource(BaseModel):
    """Path to a .codex/ folder within a project. There could be multiple of these between `cwd` and the project/repo root."""
    model_config = ConfigDict(extra="allow")

    dotCodexFolder: AbsolutePathBuf
    type: Literal["project"]

class SessionFlagsConfigLayerSource(BaseModel):
    """Session-layer overrides supplied via `-c`/`--config`."""
    model_config = ConfigDict(extra="allow")

    type: Literal["sessionFlags"]

class LegacyManagedConfigTomlFromFileConfigLayerSource(BaseModel):
    """`managed_config.toml` was designed to be a config that was loaded as the last layer on top of everything else. This scheme did not quite work out as intended, but we keep this variant as a "best effort" while we phase out `managed_config.toml` in favor of `requirements.toml`."""
    model_config = ConfigDict(extra="allow")

    file: AbsolutePathBuf
    type: Literal["legacyManagedConfigTomlFromFile"]

class LegacyManagedConfigTomlFromMdmConfigLayerSource(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["legacyManagedConfigTomlFromMdm"]

class GranularAskForApprovalGranular(BaseModel):
    model_config = ConfigDict(extra="allow")

    mcp_elicitations: bool
    request_permissions: bool = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool = False

AbsolutePathBuf: TypeAlias = str

AppToolApproval: TypeAlias = Literal["auto", "prompt", "approve"]

AppToolsConfig: TypeAlias = dict[str, Any]

ApprovalsReviewer: TypeAlias = Literal["user", "guardian_subagent"]

AskForApproval: TypeAlias = Literal["untrusted", "on-failure", "on-request", "never"] | GranularAskForApproval

ConfigLayerSource: TypeAlias = MdmConfigLayerSource | SystemConfigLayerSource | UserConfigLayerSource | ProjectConfigLayerSource | SessionFlagsConfigLayerSource | LegacyManagedConfigTomlFromFileConfigLayerSource | LegacyManagedConfigTomlFromMdmConfigLayerSource

ForcedLoginMethod: TypeAlias = Literal["chatgpt", "api"]

ReasoningEffort: TypeAlias = Literal["none", "minimal", "low", "medium", "high", "xhigh"]

ReasoningSummary: TypeAlias = Literal["auto", "concise", "detailed", "none"]

SandboxMode: TypeAlias = Literal["read-only", "workspace-write", "danger-full-access"]

ServiceTier: TypeAlias = Literal["fast", "flex"]

Verbosity: TypeAlias = Literal["low", "medium", "high"]

WebSearchContextSize: TypeAlias = Literal["low", "medium", "high"]

WebSearchMode: TypeAlias = Literal["disabled", "cached", "live"]

class ConfigReadResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    config: Config
    layers: list[Any] | None = None
    origins: dict[str, ConfigLayerMetadata]
