# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class ConfigEdit(BaseModel):
    model_config = ConfigDict(extra="allow")

    keyPath: str
    mergeStrategy: MergeStrategy
    value: Any

MergeStrategy: TypeAlias = Literal["replace", "upsert"]

class ConfigBatchWriteParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    edits: list[ConfigEdit]
    expectedVersion: str | None = None
    filePath: str | None = None
    reloadUserConfig: bool | None = None
