# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ContextCompactedNotification(BaseModel):
    """Deprecated: Use `ContextCompaction` item type instead."""
    model_config = ConfigDict(extra="allow")

    threadId: str
    turnId: str
