# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class TurnError(BaseModel):
    model_config = ConfigDict(extra="allow")

    additionalDetails: str | None = None
    codexErrorInfo: CodexErrorInfo | None = None
    message: str

class HttpConnectionFailedCodexErrorInfo(BaseModel):
    model_config = ConfigDict(extra="forbid")

    httpConnectionFailed: HttpConnectionFailedCodexErrorInfoHttpConnectionFailed

class ResponseStreamConnectionFailedCodexErrorInfo(BaseModel):
    """Failed to connect to the response SSE stream."""
    model_config = ConfigDict(extra="forbid")

    responseStreamConnectionFailed: ResponseStreamConnectionFailedCodexErrorInfoResponseStreamConnectionFailed

class ResponseStreamDisconnectedCodexErrorInfo(BaseModel):
    """The response SSE stream disconnected in the middle of a turn before completion."""
    model_config = ConfigDict(extra="forbid")

    responseStreamDisconnected: ResponseStreamDisconnectedCodexErrorInfoResponseStreamDisconnected

class ResponseTooManyFailedAttemptsCodexErrorInfo(BaseModel):
    """Reached the retry limit for responses."""
    model_config = ConfigDict(extra="forbid")

    responseTooManyFailedAttempts: ResponseTooManyFailedAttemptsCodexErrorInfoResponseTooManyFailedAttempts

class ActiveTurnNotSteerableCodexErrorInfo(BaseModel):
    """Returned when `turn/start` or `turn/steer` is submitted while the current active turn cannot accept same-turn steering, for example `/review` or manual `/compact`."""
    model_config = ConfigDict(extra="forbid")

    activeTurnNotSteerable: ActiveTurnNotSteerableCodexErrorInfoActiveTurnNotSteerable

class HttpConnectionFailedCodexErrorInfoHttpConnectionFailed(BaseModel):
    model_config = ConfigDict(extra="allow")

    httpStatusCode: int | None = None

class ResponseStreamConnectionFailedCodexErrorInfoResponseStreamConnectionFailed(BaseModel):
    model_config = ConfigDict(extra="allow")

    httpStatusCode: int | None = None

class ResponseStreamDisconnectedCodexErrorInfoResponseStreamDisconnected(BaseModel):
    model_config = ConfigDict(extra="allow")

    httpStatusCode: int | None = None

class ResponseTooManyFailedAttemptsCodexErrorInfoResponseTooManyFailedAttempts(BaseModel):
    model_config = ConfigDict(extra="allow")

    httpStatusCode: int | None = None

class ActiveTurnNotSteerableCodexErrorInfoActiveTurnNotSteerable(BaseModel):
    model_config = ConfigDict(extra="allow")

    turnKind: NonSteerableTurnKind

CodexErrorInfo: TypeAlias = Literal["contextWindowExceeded", "usageLimitExceeded", "serverOverloaded", "internalServerError", "unauthorized", "badRequest", "threadRollbackFailed", "sandboxError", "other"] | HttpConnectionFailedCodexErrorInfo | ResponseStreamConnectionFailedCodexErrorInfo | ResponseStreamDisconnectedCodexErrorInfo | ResponseTooManyFailedAttemptsCodexErrorInfo | ActiveTurnNotSteerableCodexErrorInfo

NonSteerableTurnKind: TypeAlias = Literal["review", "compact"]

class ErrorNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    error: TurnError
    threadId: str
    turnId: str
    willRetry: bool
