# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class ExperimentalFeature(BaseModel):
    model_config = ConfigDict(extra="allow")

    announcement: str | None = None
    defaultEnabled: bool
    description: str | None = None
    displayName: str | None = None
    enabled: bool
    name: str
    stage: ExperimentalFeatureStage

ExperimentalFeatureStage: TypeAlias = Literal["beta", "underDevelopment", "stable", "deprecated", "removed"]

class ExperimentalFeatureListResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    data: list[ExperimentalFeature]
    nextCursor: str | None = None
