# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import TypeAlias

from pydantic import BaseModel, ConfigDict

AbsolutePathBuf: TypeAlias = str

class FsCopyParams(BaseModel):
    """Copy a file or directory tree on the host filesystem."""
    model_config = ConfigDict(extra="allow")

    destinationPath: AbsolutePathBuf
    recursive: bool | None = None
    sourcePath: AbsolutePathBuf
