# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import TypeAlias

from pydantic import BaseModel, ConfigDict

AbsolutePathBuf: TypeAlias = str

class FsRemoveParams(BaseModel):
    """Remove a file or directory tree from the host filesystem."""
    model_config = ConfigDict(extra="allow")

    force: bool | None = None
    path: AbsolutePathBuf
    recursive: bool | None = None
