# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class FsReadDirectoryEntry(BaseModel):
    """A directory entry returned by `fs/readDirectory`."""
    model_config = ConfigDict(extra="allow")

    fileName: str
    isDirectory: bool
    isFile: bool

class FsReadDirectoryResponse(BaseModel):
    """Directory entries returned by `fs/readDirectory`."""
    model_config = ConfigDict(extra="allow")

    entries: list[FsReadDirectoryEntry]
