# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class HookOutputEntry(BaseModel):
    model_config = ConfigDict(extra="allow")

    kind: HookOutputEntryKind
    text: str

class HookRunSummary(BaseModel):
    model_config = ConfigDict(extra="allow")

    completedAt: int | None = None
    displayOrder: int
    durationMs: int | None = None
    entries: list[HookOutputEntry]
    eventName: HookEventName
    executionMode: HookExecutionMode
    handlerType: HookHandlerType
    id: str
    scope: HookScope
    sourcePath: str
    startedAt: int
    status: HookRunStatus
    statusMessage: str | None = None

HookEventName: TypeAlias = Literal["preToolUse", "postToolUse", "sessionStart", "userPromptSubmit", "stop"]

HookExecutionMode: TypeAlias = Literal["sync", "async"]

HookHandlerType: TypeAlias = Literal["command", "prompt", "agent"]

HookOutputEntryKind: TypeAlias = Literal["warning", "stop", "feedback", "context", "error"]

HookRunStatus: TypeAlias = Literal["running", "completed", "failed", "blocked", "stopped"]

HookScope: TypeAlias = Literal["thread", "turn"]

class HookCompletedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    run: HookRunSummary
    threadId: str
    turnId: str | None = None
