# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class GuardianApprovalReview(BaseModel):
    """[UNSTABLE] Temporary guardian approval review payload used by `item/autoApprovalReview/*` notifications. This shape is expected to change soon."""
    model_config = ConfigDict(extra="allow")

    rationale: str | None = None
    riskLevel: GuardianRiskLevel | None = None
    riskScore: int | None = None
    status: GuardianApprovalReviewStatus

GuardianApprovalReviewStatus: TypeAlias = Literal["inProgress", "approved", "denied", "aborted"]

GuardianRiskLevel: TypeAlias = Literal["low", "medium", "high"]

class ItemGuardianApprovalReviewStartedNotification(BaseModel):
    """[UNSTABLE] Temporary notification payload for guardian automatic approval review. This shape is expected to change soon.

TODO(ccunningham): Attach guardian review state to the reviewed tool item's lifecycle instead of sending separate standalone review notifications so the app-server API can persist and replay review state via `thread/read`."""
    model_config = ConfigDict(extra="allow")

    action: Any | None = None
    review: GuardianApprovalReview
    targetItemId: str
    threadId: str
    turnId: str
