# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict, Field


class McpServerStatus(BaseModel):
    model_config = ConfigDict(extra="allow")

    authStatus: McpAuthStatus
    name: str
    resourceTemplates: list[ResourceTemplate]
    resources: list[Resource]
    tools: dict[str, Tool]

class Resource(BaseModel):
    """A known resource that the server is capable of reading."""
    model_config = ConfigDict(extra="allow")

    meta: Any | None = Field(default=None, alias="_meta")
    annotations: Any | None = None
    description: str | None = None
    icons: list[Any] | None = None
    mimeType: str | None = None
    name: str
    size: int | None = None
    title: str | None = None
    uri: str

class ResourceTemplate(BaseModel):
    """A template description for resources available on the server."""
    model_config = ConfigDict(extra="allow")

    annotations: Any | None = None
    description: str | None = None
    mimeType: str | None = None
    name: str
    title: str | None = None
    uriTemplate: str

class Tool(BaseModel):
    """Definition for a tool the client can call."""
    model_config = ConfigDict(extra="allow")

    meta: Any | None = Field(default=None, alias="_meta")
    annotations: Any | None = None
    description: str | None = None
    icons: list[Any] | None = None
    inputSchema: Any
    name: str
    outputSchema: Any | None = None
    title: str | None = None

McpAuthStatus: TypeAlias = Literal["unsupported", "notLoggedIn", "bearerToken", "oAuth"]

class ListMcpServerStatusResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    data: list[McpServerStatus]
    nextCursor: str | None = None
