# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class ApiKeyv2LoginAccountResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["apiKey"]

class Chatgptv2LoginAccountResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    authUrl: str
    loginId: str
    type: Literal["chatgpt"]

class ChatgptDeviceCodev2LoginAccountResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    loginId: str
    type: Literal["chatgptDeviceCode"]
    userCode: str
    verificationUrl: str

class ChatgptAuthTokensv2LoginAccountResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["chatgptAuthTokens"]

LoginAccountResponse: TypeAlias = ApiKeyv2LoginAccountResponse | Chatgptv2LoginAccountResponse | ChatgptDeviceCodev2LoginAccountResponse | ChatgptAuthTokensv2LoginAccountResponse
