# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class ApiKeyv2LoginAccountParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    apiKey: str
    type: Literal["apiKey"]

class Chatgptv2LoginAccountParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["chatgpt"]

class ChatgptDeviceCodev2LoginAccountParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["chatgptDeviceCode"]

class ChatgptAuthTokensv2LoginAccountParams(BaseModel):
    """[UNSTABLE] FOR OPENAI INTERNAL USE ONLY - DO NOT USE. The access token must contain the same scopes that Codex-managed ChatGPT auth tokens have."""
    model_config = ConfigDict(extra="allow")

    accessToken: str
    chatgptAccountId: str
    chatgptPlanType: str | None = None
    type: Literal["chatgptAuthTokens"]

LoginAccountParams: TypeAlias = ApiKeyv2LoginAccountParams | Chatgptv2LoginAccountParams | ChatgptDeviceCodev2LoginAccountParams | ChatgptAuthTokensv2LoginAccountParams
