# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class Model(BaseModel):
    model_config = ConfigDict(extra="allow")

    availabilityNux: ModelAvailabilityNux | None = None
    defaultReasoningEffort: ReasoningEffort
    description: str
    displayName: str
    hidden: bool
    id: str
    inputModalities: list[InputModality] = ["text", "image"]
    isDefault: bool
    model: str
    supportedReasoningEfforts: list[ReasoningEffortOption]
    supportsPersonality: bool = False
    upgrade: str | None = None
    upgradeInfo: ModelUpgradeInfo | None = None

class ModelAvailabilityNux(BaseModel):
    model_config = ConfigDict(extra="allow")

    message: str

class ModelUpgradeInfo(BaseModel):
    model_config = ConfigDict(extra="allow")

    migrationMarkdown: str | None = None
    model: str
    modelLink: str | None = None
    upgradeCopy: str | None = None

class ReasoningEffortOption(BaseModel):
    model_config = ConfigDict(extra="allow")

    description: str
    reasoningEffort: ReasoningEffort

InputModality: TypeAlias = Literal["text", "image"]

ReasoningEffort: TypeAlias = Literal["none", "minimal", "low", "medium", "high", "xhigh"]

class ModelListResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    data: list[Model]
    nextCursor: str | None = None
