# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class PlanDeltaNotification(BaseModel):
    """EXPERIMENTAL - proposed plan streaming deltas for plan items. Clients should not assume concatenated deltas match the completed plan item content."""
    model_config = ConfigDict(extra="allow")

    delta: str
    itemId: str
    threadId: str
    turnId: str
