# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class MarketplaceInterface(BaseModel):
    model_config = ConfigDict(extra="allow")

    displayName: str | None = None

class MarketplaceLoadErrorInfo(BaseModel):
    model_config = ConfigDict(extra="allow")

    marketplacePath: AbsolutePathBuf
    message: str

class PluginInterface(BaseModel):
    model_config = ConfigDict(extra="allow")

    brandColor: str | None = None
    capabilities: list[str]
    category: str | None = None
    composerIcon: AbsolutePathBuf | None = None
    defaultPrompt: list[Any] | None = None
    developerName: str | None = None
    displayName: str | None = None
    logo: AbsolutePathBuf | None = None
    longDescription: str | None = None
    privacyPolicyUrl: str | None = None
    screenshots: list[AbsolutePathBuf]
    shortDescription: str | None = None
    termsOfServiceUrl: str | None = None
    websiteUrl: str | None = None

class PluginMarketplaceEntry(BaseModel):
    model_config = ConfigDict(extra="allow")

    interface: MarketplaceInterface | None = None
    name: str
    path: AbsolutePathBuf
    plugins: list[PluginSummary]

class PluginSummary(BaseModel):
    model_config = ConfigDict(extra="allow")

    authPolicy: PluginAuthPolicy
    enabled: bool
    id: str
    installPolicy: PluginInstallPolicy
    installed: bool
    interface: PluginInterface | None = None
    name: str
    source: PluginSource

class LocalPluginSource(BaseModel):
    model_config = ConfigDict(extra="allow")

    path: AbsolutePathBuf
    type: Literal["local"]

AbsolutePathBuf: TypeAlias = str

PluginAuthPolicy: TypeAlias = Literal["ON_INSTALL", "ON_USE"]

PluginInstallPolicy: TypeAlias = Literal["NOT_AVAILABLE", "AVAILABLE", "INSTALLED_BY_DEFAULT"]

PluginSource: TypeAlias = LocalPluginSource

class PluginListResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    featuredPluginIds: list[str] = []
    marketplaceLoadErrors: list[MarketplaceLoadErrorInfo] = []
    marketplaces: list[PluginMarketplaceEntry]
    remoteSyncError: str | None = None
