# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class AppSummary(BaseModel):
    """EXPERIMENTAL - app metadata summary for plugin responses."""
    model_config = ConfigDict(extra="allow")

    description: str | None = None
    id: str
    installUrl: str | None = None
    name: str
    needsAuth: bool

class PluginDetail(BaseModel):
    model_config = ConfigDict(extra="allow")

    apps: list[AppSummary]
    description: str | None = None
    marketplaceName: str
    marketplacePath: AbsolutePathBuf
    mcpServers: list[str]
    skills: list[SkillSummary]
    summary: PluginSummary

class PluginInterface(BaseModel):
    model_config = ConfigDict(extra="allow")

    brandColor: str | None = None
    capabilities: list[str]
    category: str | None = None
    composerIcon: AbsolutePathBuf | None = None
    defaultPrompt: list[Any] | None = None
    developerName: str | None = None
    displayName: str | None = None
    logo: AbsolutePathBuf | None = None
    longDescription: str | None = None
    privacyPolicyUrl: str | None = None
    screenshots: list[AbsolutePathBuf]
    shortDescription: str | None = None
    termsOfServiceUrl: str | None = None
    websiteUrl: str | None = None

class PluginSummary(BaseModel):
    model_config = ConfigDict(extra="allow")

    authPolicy: PluginAuthPolicy
    enabled: bool
    id: str
    installPolicy: PluginInstallPolicy
    installed: bool
    interface: PluginInterface | None = None
    name: str
    source: PluginSource

class SkillInterface(BaseModel):
    model_config = ConfigDict(extra="allow")

    brandColor: str | None = None
    defaultPrompt: str | None = None
    displayName: str | None = None
    iconLarge: str | None = None
    iconSmall: str | None = None
    shortDescription: str | None = None

class SkillSummary(BaseModel):
    model_config = ConfigDict(extra="allow")

    description: str
    enabled: bool
    interface: SkillInterface | None = None
    name: str
    path: str
    shortDescription: str | None = None

class LocalPluginSource(BaseModel):
    model_config = ConfigDict(extra="allow")

    path: AbsolutePathBuf
    type: Literal["local"]

AbsolutePathBuf: TypeAlias = str

PluginAuthPolicy: TypeAlias = Literal["ON_INSTALL", "ON_USE"]

PluginInstallPolicy: TypeAlias = Literal["NOT_AVAILABLE", "AVAILABLE", "INSTALLED_BY_DEFAULT"]

PluginSource: TypeAlias = LocalPluginSource

class PluginReadResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    plugin: PluginDetail
