# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, TypeAlias

from pydantic import BaseModel, ConfigDict

AbsolutePathBuf: TypeAlias = str

class PluginListParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    cwds: list[Any] | None = None
    forceRemoteSync: bool | None = None
