# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class AppSummary(BaseModel):
    """EXPERIMENTAL - app metadata summary for plugin responses."""
    model_config = ConfigDict(extra="allow")

    description: str | None = None
    id: str
    installUrl: str | None = None
    name: str
    needsAuth: bool

PluginAuthPolicy: TypeAlias = Literal["ON_INSTALL", "ON_USE"]

class PluginInstallResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    appsNeedingAuth: list[AppSummary]
    authPolicy: PluginAuthPolicy
