# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class UncommittedChangesReviewTarget(BaseModel):
    """Review the working tree: staged, unstaged, and untracked files."""
    model_config = ConfigDict(extra="allow")

    type: Literal["uncommittedChanges"]

class BaseBranchReviewTarget(BaseModel):
    """Review changes between the current branch and the given base branch."""
    model_config = ConfigDict(extra="allow")

    branch: str
    type: Literal["baseBranch"]

class CommitReviewTarget(BaseModel):
    """Review the changes introduced by a specific commit."""
    model_config = ConfigDict(extra="allow")

    sha: str
    title: str | None = None
    type: Literal["commit"]

class CustomReviewTarget(BaseModel):
    """Arbitrary instructions, equivalent to the old free-form prompt."""
    model_config = ConfigDict(extra="allow")

    instructions: str
    type: Literal["custom"]

ReviewDelivery: TypeAlias = Literal["inline", "detached"]

ReviewTarget: TypeAlias = UncommittedChangesReviewTarget | BaseBranchReviewTarget | CommitReviewTarget | CustomReviewTarget

class ReviewStartParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    delivery: ReviewDelivery | None = None
    target: ReviewTarget
    threadId: str
