# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class SkillDependencies(BaseModel):
    model_config = ConfigDict(extra="allow")

    tools: list[SkillToolDependency]

class SkillErrorInfo(BaseModel):
    model_config = ConfigDict(extra="allow")

    message: str
    path: str

class SkillInterface(BaseModel):
    model_config = ConfigDict(extra="allow")

    brandColor: str | None = None
    defaultPrompt: str | None = None
    displayName: str | None = None
    iconLarge: str | None = None
    iconSmall: str | None = None
    shortDescription: str | None = None

class SkillMetadata(BaseModel):
    model_config = ConfigDict(extra="allow")

    dependencies: SkillDependencies | None = None
    description: str
    enabled: bool
    interface: SkillInterface | None = None
    name: str
    path: str
    scope: SkillScope
    shortDescription: str | None = None

class SkillToolDependency(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str | None = None
    description: str | None = None
    transport: str | None = None
    type: str
    url: str | None = None
    value: str

class SkillsListEntry(BaseModel):
    model_config = ConfigDict(extra="allow")

    cwd: str
    errors: list[SkillErrorInfo]
    skills: list[SkillMetadata]

SkillScope: TypeAlias = Literal["user", "repo", "system", "admin"]

class SkillsListResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    data: list[SkillsListEntry]
