# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict


class SkillsListExtraRootsForCwd(BaseModel):
    model_config = ConfigDict(extra="allow")

    cwd: str
    extraUserRoots: list[str]

class SkillsListParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    cwds: list[str] | None = None
    forceReload: bool | None = None
    perCwdExtraUserRoots: list[Any] | None = None
