# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class DynamicToolSpec(BaseModel):
    model_config = ConfigDict(extra="allow")

    deferLoading: bool | None = None
    description: str
    inputSchema: Any
    name: str

class GranularAskForApproval(BaseModel):
    model_config = ConfigDict(extra="forbid")

    granular: GranularAskForApprovalGranular

class GranularAskForApprovalGranular(BaseModel):
    model_config = ConfigDict(extra="allow")

    mcp_elicitations: bool
    request_permissions: bool = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool = False

ApprovalsReviewer: TypeAlias = Literal["user", "guardian_subagent"]

AskForApproval: TypeAlias = Literal["untrusted", "on-failure", "on-request", "never"] | GranularAskForApproval

Personality: TypeAlias = Literal["none", "friendly", "pragmatic"]

SandboxMode: TypeAlias = Literal["read-only", "workspace-write", "danger-full-access"]

ServiceTier: TypeAlias = Literal["fast", "flex"]

class ThreadStartParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = None
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    serviceName: str | None = None
    ephemeral: bool | None = None
    personality: Personality | None = None
    sandbox: SandboxMode | None = None
    model: str | None = None
    modelProvider: str | None = None
    serviceTier: ServiceTier | None = None
