# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class ByteRange(BaseModel):
    model_config = ConfigDict(extra="allow")

    end: int
    start: int

class CollabAgentState(BaseModel):
    model_config = ConfigDict(extra="allow")

    message: str | None = None
    status: CollabAgentStatus

class FileUpdateChange(BaseModel):
    model_config = ConfigDict(extra="allow")

    diff: str
    kind: PatchChangeKind
    path: str

class GitInfo(BaseModel):
    model_config = ConfigDict(extra="allow")

    branch: str | None = None
    originUrl: str | None = None
    sha: str | None = None

class HookPromptFragment(BaseModel):
    model_config = ConfigDict(extra="allow")

    hookRunId: str
    text: str

class McpToolCallError(BaseModel):
    model_config = ConfigDict(extra="allow")

    message: str

class McpToolCallResult(BaseModel):
    model_config = ConfigDict(extra="allow")

    content: list[Any]
    structuredContent: Any | None = None

class MemoryCitation(BaseModel):
    model_config = ConfigDict(extra="allow")

    entries: list[MemoryCitationEntry]
    threadIds: list[str]

class MemoryCitationEntry(BaseModel):
    model_config = ConfigDict(extra="allow")

    lineEnd: int
    lineStart: int
    note: str
    path: str

class TextElement(BaseModel):
    model_config = ConfigDict(extra="allow")

    byteRange: ByteRange
    placeholder: str | None = None

class Thread(BaseModel):
    model_config = ConfigDict(extra="allow")

    agentNickname: str | None = None
    agentRole: str | None = None
    cliVersion: str
    createdAt: int
    cwd: str
    ephemeral: bool
    gitInfo: GitInfo | None = None
    id: str
    modelProvider: str
    name: str | None = None
    path: str | None = None
    preview: str
    source: SessionSource
    status: ThreadStatus
    turns: list[Turn]
    updatedAt: int

class Turn(BaseModel):
    model_config = ConfigDict(extra="allow")

    error: TurnError | None = None
    id: str
    items: list[ThreadItem]
    status: TurnStatus

class TurnError(BaseModel):
    model_config = ConfigDict(extra="allow")

    additionalDetails: str | None = None
    codexErrorInfo: CodexErrorInfo | None = None
    message: str

class HttpConnectionFailedCodexErrorInfo(BaseModel):
    model_config = ConfigDict(extra="forbid")

    httpConnectionFailed: HttpConnectionFailedCodexErrorInfoHttpConnectionFailed

class ResponseStreamConnectionFailedCodexErrorInfo(BaseModel):
    """Failed to connect to the response SSE stream."""
    model_config = ConfigDict(extra="forbid")

    responseStreamConnectionFailed: ResponseStreamConnectionFailedCodexErrorInfoResponseStreamConnectionFailed

class ResponseStreamDisconnectedCodexErrorInfo(BaseModel):
    """The response SSE stream disconnected in the middle of a turn before completion."""
    model_config = ConfigDict(extra="forbid")

    responseStreamDisconnected: ResponseStreamDisconnectedCodexErrorInfoResponseStreamDisconnected

class ResponseTooManyFailedAttemptsCodexErrorInfo(BaseModel):
    """Reached the retry limit for responses."""
    model_config = ConfigDict(extra="forbid")

    responseTooManyFailedAttempts: ResponseTooManyFailedAttemptsCodexErrorInfoResponseTooManyFailedAttempts

class ActiveTurnNotSteerableCodexErrorInfo(BaseModel):
    """Returned when `turn/start` or `turn/steer` is submitted while the current active turn cannot accept same-turn steering, for example `/review` or manual `/compact`."""
    model_config = ConfigDict(extra="forbid")

    activeTurnNotSteerable: ActiveTurnNotSteerableCodexErrorInfoActiveTurnNotSteerable

class ReadCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    name: str
    path: str
    type: Literal["read"]

class ListFilesCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    path: str | None = None
    type: Literal["listFiles"]

class SearchCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    path: str | None = None
    query: str | None = None
    type: Literal["search"]

class UnknownCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    type: Literal["unknown"]

class InputTextDynamicToolCallOutputContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["inputText"]

class InputImageDynamicToolCallOutputContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    imageUrl: str
    type: Literal["inputImage"]

class AddPatchChangeKind(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["add"]

class DeletePatchChangeKind(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["delete"]

class UpdatePatchChangeKind(BaseModel):
    model_config = ConfigDict(extra="allow")

    move_path: str | None = None
    type: Literal["update"]

class CustomSessionSource(BaseModel):
    model_config = ConfigDict(extra="forbid")

    custom: str

class SubAgentSessionSource(BaseModel):
    model_config = ConfigDict(extra="forbid")

    subAgent: SubAgentSource

class ThreadSpawnSubAgentSource(BaseModel):
    model_config = ConfigDict(extra="forbid")

    thread_spawn: ThreadSpawnSubAgentSourceThreadSpawn

class OtherSubAgentSource(BaseModel):
    model_config = ConfigDict(extra="forbid")

    other: str

class UserMessageThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    content: list[UserInput]
    id: str
    type: Literal["userMessage"]

class HookPromptThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    fragments: list[HookPromptFragment]
    id: str
    type: Literal["hookPrompt"]

class AgentMessageThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    memoryCitation: MemoryCitation | None = None
    phase: MessagePhase | None = None
    text: str
    type: Literal["agentMessage"]

class PlanThreadItem(BaseModel):
    """EXPERIMENTAL - proposed plan item content. The completed plan item is authoritative and may not match the concatenation of `PlanDelta` text."""
    model_config = ConfigDict(extra="allow")

    id: str
    text: str
    type: Literal["plan"]

class ReasoningThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    content: list[str] = []
    id: str
    summary: list[str] = []
    type: Literal["reasoning"]

class CommandExecutionThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    aggregatedOutput: str | None = None
    command: str
    commandActions: list[CommandAction]
    cwd: str
    durationMs: int | None = None
    exitCode: int | None = None
    id: str
    processId: str | None = None
    source: CommandExecutionSource = "agent"
    status: CommandExecutionStatus
    type: Literal["commandExecution"]

class FileChangeThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    changes: list[FileUpdateChange]
    id: str
    status: PatchApplyStatus
    type: Literal["fileChange"]

class McpToolCallThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    arguments: Any
    durationMs: int | None = None
    error: McpToolCallError | None = None
    id: str
    result: McpToolCallResult | None = None
    server: str
    status: McpToolCallStatus
    tool: str
    type: Literal["mcpToolCall"]

class DynamicToolCallThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    arguments: Any
    contentItems: list[Any] | None = None
    durationMs: int | None = None
    id: str
    status: DynamicToolCallStatus
    success: bool | None = None
    tool: str
    type: Literal["dynamicToolCall"]

class CollabAgentToolCallThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    agentsStates: dict[str, CollabAgentState]
    id: str
    model: str | None = None
    prompt: str | None = None
    reasoningEffort: ReasoningEffort | None = None
    receiverThreadIds: list[str]
    senderThreadId: str
    status: CollabAgentToolCallStatus
    tool: CollabAgentTool
    type: Literal["collabAgentToolCall"]

class WebSearchThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    action: WebSearchAction | None = None
    id: str
    query: str
    type: Literal["webSearch"]

class ImageViewThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    path: str
    type: Literal["imageView"]

class ImageGenerationThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    result: str
    revisedPrompt: str | None = None
    savedPath: str | None = None
    status: str
    type: Literal["imageGeneration"]

class EnteredReviewModeThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    review: str
    type: Literal["enteredReviewMode"]

class ExitedReviewModeThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    review: str
    type: Literal["exitedReviewMode"]

class ContextCompactionThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    type: Literal["contextCompaction"]

class NotLoadedThreadStatus(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["notLoaded"]

class IdleThreadStatus(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["idle"]

class SystemErrorThreadStatus(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["systemError"]

class ActiveThreadStatus(BaseModel):
    model_config = ConfigDict(extra="allow")

    activeFlags: list[ThreadActiveFlag]
    type: Literal["active"]

class TextUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    text_elements: list[TextElement] = []
    type: Literal["text"]

class ImageUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["image"]
    url: str

class LocalImageUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    path: str
    type: Literal["localImage"]

class SkillUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    path: str
    type: Literal["skill"]

class MentionUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    path: str
    type: Literal["mention"]

class SearchWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    queries: list[Any] | None = None
    query: str | None = None
    type: Literal["search"]

class OpenPageWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["openPage"]
    url: str | None = None

class FindInPageWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    pattern: str | None = None
    type: Literal["findInPage"]
    url: str | None = None

class OtherWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["other"]

class HttpConnectionFailedCodexErrorInfoHttpConnectionFailed(BaseModel):
    model_config = ConfigDict(extra="allow")

    httpStatusCode: int | None = None

class ResponseStreamConnectionFailedCodexErrorInfoResponseStreamConnectionFailed(BaseModel):
    model_config = ConfigDict(extra="allow")

    httpStatusCode: int | None = None

class ResponseStreamDisconnectedCodexErrorInfoResponseStreamDisconnected(BaseModel):
    model_config = ConfigDict(extra="allow")

    httpStatusCode: int | None = None

class ResponseTooManyFailedAttemptsCodexErrorInfoResponseTooManyFailedAttempts(BaseModel):
    model_config = ConfigDict(extra="allow")

    httpStatusCode: int | None = None

class ActiveTurnNotSteerableCodexErrorInfoActiveTurnNotSteerable(BaseModel):
    model_config = ConfigDict(extra="allow")

    turnKind: NonSteerableTurnKind

class ThreadSpawnSubAgentSourceThreadSpawn(BaseModel):
    model_config = ConfigDict(extra="allow")

    agent_nickname: str | None = None
    agent_path: AgentPath | None = None
    agent_role: str | None = None
    depth: int
    parent_thread_id: ThreadId

AgentPath: TypeAlias = str

CodexErrorInfo: TypeAlias = Literal["contextWindowExceeded", "usageLimitExceeded", "serverOverloaded", "internalServerError", "unauthorized", "badRequest", "threadRollbackFailed", "sandboxError", "other"] | HttpConnectionFailedCodexErrorInfo | ResponseStreamConnectionFailedCodexErrorInfo | ResponseStreamDisconnectedCodexErrorInfo | ResponseTooManyFailedAttemptsCodexErrorInfo | ActiveTurnNotSteerableCodexErrorInfo

CollabAgentStatus: TypeAlias = Literal["pendingInit", "running", "interrupted", "completed", "errored", "shutdown", "notFound"]

CollabAgentTool: TypeAlias = Literal["spawnAgent", "sendInput", "resumeAgent", "wait", "closeAgent"]

CollabAgentToolCallStatus: TypeAlias = Literal["inProgress", "completed", "failed"]

CommandAction: TypeAlias = ReadCommandAction | ListFilesCommandAction | SearchCommandAction | UnknownCommandAction

CommandExecutionSource: TypeAlias = Literal["agent", "userShell", "unifiedExecStartup", "unifiedExecInteraction"]

CommandExecutionStatus: TypeAlias = Literal["inProgress", "completed", "failed", "declined"]

DynamicToolCallOutputContentItem: TypeAlias = InputTextDynamicToolCallOutputContentItem | InputImageDynamicToolCallOutputContentItem

DynamicToolCallStatus: TypeAlias = Literal["inProgress", "completed", "failed"]

McpToolCallStatus: TypeAlias = Literal["inProgress", "completed", "failed"]

MessagePhase: TypeAlias = Literal["commentary", "final_answer"]

NonSteerableTurnKind: TypeAlias = Literal["review", "compact"]

PatchApplyStatus: TypeAlias = Literal["inProgress", "completed", "failed", "declined"]

PatchChangeKind: TypeAlias = AddPatchChangeKind | DeletePatchChangeKind | UpdatePatchChangeKind

ReasoningEffort: TypeAlias = Literal["none", "minimal", "low", "medium", "high", "xhigh"]

SessionSource: TypeAlias = Literal["cli", "vscode", "exec", "appServer", "unknown"] | CustomSessionSource | SubAgentSessionSource

SubAgentSource: TypeAlias = Literal["review", "compact", "memory_consolidation"] | ThreadSpawnSubAgentSource | OtherSubAgentSource

ThreadActiveFlag: TypeAlias = Literal["waitingOnApproval", "waitingOnUserInput"]

ThreadId: TypeAlias = str

ThreadItem: TypeAlias = UserMessageThreadItem | HookPromptThreadItem | AgentMessageThreadItem | PlanThreadItem | ReasoningThreadItem | CommandExecutionThreadItem | FileChangeThreadItem | McpToolCallThreadItem | DynamicToolCallThreadItem | CollabAgentToolCallThreadItem | WebSearchThreadItem | ImageViewThreadItem | ImageGenerationThreadItem | EnteredReviewModeThreadItem | ExitedReviewModeThreadItem | ContextCompactionThreadItem

ThreadStatus: TypeAlias = NotLoadedThreadStatus | IdleThreadStatus | SystemErrorThreadStatus | ActiveThreadStatus

TurnStatus: TypeAlias = Literal["completed", "interrupted", "failed", "inProgress"]

UserInput: TypeAlias = TextUserInput | ImageUserInput | LocalImageUserInput | SkillUserInput | MentionUserInput

WebSearchAction: TypeAlias = SearchWebSearchAction | OpenPageWebSearchAction | FindInPageWebSearchAction | OtherWebSearchAction

class ThreadListResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    data: list[Thread]
    nextCursor: str | None = None
