# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class GhostCommit(BaseModel):
    """Details of a ghost commit created from a repository state."""
    model_config = ConfigDict(extra="allow")

    id: str
    parent: str | None = None
    preexisting_untracked_dirs: list[str]
    preexisting_untracked_files: list[str]

class GranularAskForApproval(BaseModel):
    model_config = ConfigDict(extra="forbid")

    granular: GranularAskForApprovalGranular

class InputTextContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["input_text"]

class InputImageContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    image_url: str
    type: Literal["input_image"]

class OutputTextContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["output_text"]

class InputTextFunctionCallOutputContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["input_text"]

class InputImageFunctionCallOutputContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    detail: ImageDetail | None = None
    image_url: str
    type: Literal["input_image"]

class ExecLocalShellAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: list[str]
    env: dict[str, Any] | None = None
    timeout_ms: int | None = None
    type: Literal["exec"]
    user: str | None = None
    working_directory: str | None = None

class ReasoningTextReasoningItemContent(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["reasoning_text"]

class TextReasoningItemContent(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["text"]

class SummaryTextReasoningItemReasoningSummary(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["summary_text"]

class MessageResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    content: list[ContentItem]
    end_turn: bool | None = None
    id: str | None = None
    phase: MessagePhase | None = None
    role: str
    type: Literal["message"]

class ReasoningResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    content: list[Any] | None = None
    encrypted_content: str | None = None
    summary: list[ReasoningItemReasoningSummary]
    type: Literal["reasoning"]

class LocalShellCallResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    action: LocalShellAction
    call_id: str | None = None
    id: str | None = None
    status: LocalShellStatus
    type: Literal["local_shell_call"]

class FunctionCallResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    arguments: str
    call_id: str
    id: str | None = None
    name: str
    namespace: str | None = None
    type: Literal["function_call"]

class ToolSearchCallResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    arguments: Any
    call_id: str | None = None
    execution: str
    id: str | None = None
    status: str | None = None
    type: Literal["tool_search_call"]

class FunctionCallOutputResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    call_id: str
    output: FunctionCallOutputBody
    type: Literal["function_call_output"]

class CustomToolCallResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    call_id: str
    id: str | None = None
    input: str
    name: str
    status: str | None = None
    type: Literal["custom_tool_call"]

class CustomToolCallOutputResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    call_id: str
    name: str | None = None
    output: FunctionCallOutputBody
    type: Literal["custom_tool_call_output"]

class ToolSearchOutputResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    call_id: str | None = None
    execution: str
    status: str
    tools: list[Any]
    type: Literal["tool_search_output"]

class WebSearchCallResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    action: ResponsesApiWebSearchAction | None = None
    id: str | None = None
    status: str | None = None
    type: Literal["web_search_call"]

class ImageGenerationCallResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    result: str
    revised_prompt: str | None = None
    status: str
    type: Literal["image_generation_call"]

class GhostSnapshotResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    ghost_commit: GhostCommit
    type: Literal["ghost_snapshot"]

class CompactionResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    encrypted_content: str
    type: Literal["compaction"]

class OtherResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["other"]

class SearchResponsesApiWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    queries: list[Any] | None = None
    query: str | None = None
    type: Literal["search"]

class OpenPageResponsesApiWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["open_page"]
    url: str | None = None

class FindInPageResponsesApiWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    pattern: str | None = None
    type: Literal["find_in_page"]
    url: str | None = None

class OtherResponsesApiWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["other"]

class GranularAskForApprovalGranular(BaseModel):
    model_config = ConfigDict(extra="allow")

    mcp_elicitations: bool
    request_permissions: bool = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool = False

ApprovalsReviewer: TypeAlias = Literal["user", "guardian_subagent"]

AskForApproval: TypeAlias = Literal["untrusted", "on-failure", "on-request", "never"] | GranularAskForApproval

ContentItem: TypeAlias = InputTextContentItem | InputImageContentItem | OutputTextContentItem

FunctionCallOutputContentItem: TypeAlias = InputTextFunctionCallOutputContentItem | InputImageFunctionCallOutputContentItem

FunctionCallOutputBody: TypeAlias = str | list[FunctionCallOutputContentItem]

ImageDetail: TypeAlias = Literal["auto", "low", "high", "original"]

LocalShellAction: TypeAlias = ExecLocalShellAction

LocalShellStatus: TypeAlias = Literal["completed", "in_progress", "incomplete"]

MessagePhase: TypeAlias = Literal["commentary", "final_answer"]

Personality: TypeAlias = Literal["none", "friendly", "pragmatic"]

ReasoningItemContent: TypeAlias = ReasoningTextReasoningItemContent | TextReasoningItemContent

ReasoningItemReasoningSummary: TypeAlias = SummaryTextReasoningItemReasoningSummary

ResponseItem: TypeAlias = MessageResponseItem | ReasoningResponseItem | LocalShellCallResponseItem | FunctionCallResponseItem | ToolSearchCallResponseItem | FunctionCallOutputResponseItem | CustomToolCallResponseItem | CustomToolCallOutputResponseItem | ToolSearchOutputResponseItem | WebSearchCallResponseItem | ImageGenerationCallResponseItem | GhostSnapshotResponseItem | CompactionResponseItem | OtherResponseItem

ResponsesApiWebSearchAction: TypeAlias = SearchResponsesApiWebSearchAction | OpenPageResponsesApiWebSearchAction | FindInPageResponsesApiWebSearchAction | OtherResponsesApiWebSearchAction

SandboxMode: TypeAlias = Literal["read-only", "workspace-write", "danger-full-access"]

ServiceTier: TypeAlias = Literal["fast", "flex"]

class ThreadResumeParams(BaseModel):
    """There are three ways to resume a thread: 1. By thread_id: load the thread from disk by thread_id and resume it. 2. By history: instantiate the thread from memory and resume it. 3. By path: load the thread from disk by path and resume it.

The precedence is: history > path > thread_id. If using history or path, the thread_id param will be ignored.

Prefer using thread_id whenever possible."""
    model_config = ConfigDict(extra="allow")

    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = None
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    serviceTier: ServiceTier | None = None
    model: str | None = None
    modelProvider: str | None = None
    threadId: str
    sandbox: SandboxMode | None = None
    personality: Personality | None = None
