# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class GranularAskForApproval(BaseModel):
    model_config = ConfigDict(extra="forbid")

    granular: GranularAskForApprovalGranular

class GranularAskForApprovalGranular(BaseModel):
    model_config = ConfigDict(extra="allow")

    mcp_elicitations: bool
    request_permissions: bool = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool = False

ApprovalsReviewer: TypeAlias = Literal["user", "guardian_subagent"]

AskForApproval: TypeAlias = Literal["untrusted", "on-failure", "on-request", "never"] | GranularAskForApproval

SandboxMode: TypeAlias = Literal["read-only", "workspace-write", "danger-full-access"]

ServiceTier: TypeAlias = Literal["fast", "flex"]

class ThreadForkParams(BaseModel):
    """There are two ways to fork a thread: 1. By thread_id: load the thread from disk by thread_id and fork it into a new thread. 2. By path: load the thread from disk by path and fork it into a new thread.

If using path, the thread_id param will be ignored.

Prefer using thread_id whenever possible."""
    model_config = ConfigDict(extra="allow")

    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = None
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    ephemeral: bool | None = None
    model: str | None = None
    modelProvider: str | None = None
    serviceTier: ServiceTier | None = None
    threadId: str
    sandbox: SandboxMode | None = None
