# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict

RealtimeConversationVersion: TypeAlias = Literal["v1", "v2"]

class ThreadRealtimeStartedNotification(BaseModel):
    """EXPERIMENTAL - emitted when thread realtime startup is accepted."""
    model_config = ConfigDict(extra="allow")

    sessionId: str | None = None
    threadId: str
    version: RealtimeConversationVersion
