# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict

ThreadSortKey: TypeAlias = Literal["created_at", "updated_at"]

ThreadSourceKind: TypeAlias = Literal["cli", "vscode", "exec", "appServer", "subAgent", "subAgentReview", "subAgentCompact", "subAgentThreadSpawn", "subAgentOther", "unknown"]

class ThreadListParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    archived: bool | None = None
    cursor: str | None = None
    cwd: str | None = None
    limit: int | None = None
    modelProviders: list[Any] | None = None
    searchTerm: str | None = None
    sortKey: ThreadSortKey | None = None
    sourceKinds: list[Any] | None = None
