# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class NotLoadedThreadStatus(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["notLoaded"]

class IdleThreadStatus(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["idle"]

class SystemErrorThreadStatus(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["systemError"]

class ActiveThreadStatus(BaseModel):
    model_config = ConfigDict(extra="allow")

    activeFlags: list[ThreadActiveFlag]
    type: Literal["active"]

ThreadActiveFlag: TypeAlias = Literal["waitingOnApproval", "waitingOnUserInput"]

ThreadStatus: TypeAlias = NotLoadedThreadStatus | IdleThreadStatus | SystemErrorThreadStatus | ActiveThreadStatus

class ThreadStatusChangedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    status: ThreadStatus
    threadId: str
