# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class ByteRange(BaseModel):
    model_config = ConfigDict(extra="allow")

    end: int
    start: int

class CollaborationMode(BaseModel):
    """Collaboration mode for a Codex session."""
    model_config = ConfigDict(extra="allow")

    mode: ModeKind
    settings: Settings

class Settings(BaseModel):
    """Settings for a collaboration mode."""
    model_config = ConfigDict(extra="allow")

    developer_instructions: str | None = None
    model: str
    reasoning_effort: ReasoningEffort | None = None

class TextElement(BaseModel):
    model_config = ConfigDict(extra="allow")

    byteRange: ByteRange
    placeholder: str | None = None

class GranularAskForApproval(BaseModel):
    model_config = ConfigDict(extra="forbid")

    granular: GranularAskForApprovalGranular

class RestrictedReadOnlyAccess(BaseModel):
    model_config = ConfigDict(extra="allow")

    includePlatformDefaults: bool = True
    readableRoots: list[AbsolutePathBuf] = []
    type: Literal["restricted"]

class FullAccessReadOnlyAccess(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["fullAccess"]

class DangerFullAccessSandboxPolicy(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["dangerFullAccess"]

class ReadOnlySandboxPolicy(BaseModel):
    model_config = ConfigDict(extra="allow")

    access: ReadOnlyAccess = {"type": "fullAccess"}
    networkAccess: bool = False
    type: Literal["readOnly"]

class ExternalSandboxSandboxPolicy(BaseModel):
    model_config = ConfigDict(extra="allow")

    networkAccess: NetworkAccess = "restricted"
    type: Literal["externalSandbox"]

class WorkspaceWriteSandboxPolicy(BaseModel):
    model_config = ConfigDict(extra="allow")

    excludeSlashTmp: bool = False
    excludeTmpdirEnvVar: bool = False
    networkAccess: bool = False
    readOnlyAccess: ReadOnlyAccess = {"type": "fullAccess"}
    type: Literal["workspaceWrite"]
    writableRoots: list[AbsolutePathBuf] = []

class TextUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    text_elements: list[TextElement] = []
    type: Literal["text"]

class ImageUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["image"]
    url: str

class LocalImageUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    path: str
    type: Literal["localImage"]

class SkillUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    path: str
    type: Literal["skill"]

class MentionUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    path: str
    type: Literal["mention"]

class GranularAskForApprovalGranular(BaseModel):
    model_config = ConfigDict(extra="allow")

    mcp_elicitations: bool
    request_permissions: bool = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool = False

AbsolutePathBuf: TypeAlias = str

ApprovalsReviewer: TypeAlias = Literal["user", "guardian_subagent"]

AskForApproval: TypeAlias = Literal["untrusted", "on-failure", "on-request", "never"] | GranularAskForApproval

ModeKind: TypeAlias = Literal["plan", "default"]

NetworkAccess: TypeAlias = Literal["restricted", "enabled"]

Personality: TypeAlias = Literal["none", "friendly", "pragmatic"]

ReadOnlyAccess: TypeAlias = RestrictedReadOnlyAccess | FullAccessReadOnlyAccess

ReasoningEffort: TypeAlias = Literal["none", "minimal", "low", "medium", "high", "xhigh"]

ReasoningSummary: TypeAlias = Literal["auto", "concise", "detailed", "none"]

SandboxPolicy: TypeAlias = DangerFullAccessSandboxPolicy | ReadOnlySandboxPolicy | ExternalSandboxSandboxPolicy | WorkspaceWriteSandboxPolicy

ServiceTier: TypeAlias = Literal["fast", "flex"]

UserInput: TypeAlias = TextUserInput | ImageUserInput | LocalImageUserInput | SkillUserInput | MentionUserInput

class TurnStartParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = None
    threadId: str
    cwd: str | None = None
    effort: ReasoningEffort | None = None
    input: list[UserInput]
    model: str | None = None
    outputSchema: Any | None = None
    personality: Personality | None = None
    sandboxPolicy: SandboxPolicy | None = None
    serviceTier: ServiceTier | None = None
    summary: ReasoningSummary | None = None
