# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class ByteRange(BaseModel):
    model_config = ConfigDict(extra="allow")

    end: int
    start: int

class TextElement(BaseModel):
    model_config = ConfigDict(extra="allow")

    byteRange: ByteRange
    placeholder: str | None = None

class TextUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    text_elements: list[TextElement] = []
    type: Literal["text"]

class ImageUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["image"]
    url: str

class LocalImageUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    path: str
    type: Literal["localImage"]

class SkillUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    path: str
    type: Literal["skill"]

class MentionUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    path: str
    type: Literal["mention"]

UserInput: TypeAlias = TextUserInput | ImageUserInput | LocalImageUserInput | SkillUserInput | MentionUserInput

class TurnSteerParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    expectedTurnId: str
    input: list[UserInput]
    threadId: str
