# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class AddFileChange(BaseModel):
    model_config = ConfigDict(extra="allow")

    content: str
    type: Literal["add"]

class DeleteFileChange(BaseModel):
    model_config = ConfigDict(extra="allow")

    content: str
    type: Literal["delete"]

class UpdateFileChange(BaseModel):
    model_config = ConfigDict(extra="allow")

    move_path: str | None = None
    type: Literal["update"]
    unified_diff: str

FileChange: TypeAlias = AddFileChange | DeleteFileChange | UpdateFileChange

ThreadId: TypeAlias = str

class ApplyPatchApprovalParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    callId: str
    conversationId: ThreadId
    fileChanges: dict[str, FileChange]
    grantRoot: str | None = None
    reason: str | None = None
