# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class AppsListParams(BaseModel):
    """EXPERIMENTAL - list available apps/connectors."""
    model_config = ConfigDict(extra="allow")

    cursor: str | None = None
    forceRefetch: bool | None = None
    limit: int | None = None
    threadId: str | None = None

class ByteRange(BaseModel):
    model_config = ConfigDict(extra="allow")

    end: int
    start: int

class CancelLoginAccountParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    loginId: str

class ClientInfo(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    title: str | None = None
    version: str

class CollaborationMode(BaseModel):
    """Collaboration mode for a Codex session."""
    model_config = ConfigDict(extra="allow")

    mode: ModeKind
    settings: Settings

class WindowsSandboxSetupStartParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    cwd: AbsolutePathBuf | None = None
    mode: WindowsSandboxSetupMode

class CommandExecParams(BaseModel):
    """Run a standalone command (argv vector) in the server sandbox without creating a thread or turn.

The final `command/exec` response is deferred until the process exits and is sent only after all `command/exec/outputDelta` notifications for that connection have been emitted."""
    model_config = ConfigDict(extra="allow")

    command: list[str]
    cwd: str | None = None
    disableOutputCap: bool | None = None
    disableTimeout: bool | None = None
    env: dict[str, Any] | None = None
    outputBytesCap: int | None = None
    processId: str | None = None
    sandboxPolicy: SandboxPolicy | None = None
    size: CommandExecTerminalSize | None = None
    streamStdin: bool | None = None
    streamStdoutStderr: bool | None = None
    timeoutMs: int | None = None
    tty: bool | None = None

class CommandExecResizeParams(BaseModel):
    """Resize a running PTY-backed `command/exec` session."""
    model_config = ConfigDict(extra="allow")

    processId: str
    size: CommandExecTerminalSize

class CommandExecTerminalSize(BaseModel):
    """PTY size in character cells for `command/exec` PTY sessions."""
    model_config = ConfigDict(extra="allow")

    cols: int
    rows: int

class CommandExecTerminateParams(BaseModel):
    """Terminate a running `command/exec` session."""
    model_config = ConfigDict(extra="allow")

    processId: str

class CommandExecWriteParams(BaseModel):
    """Write stdin bytes to a running `command/exec` session, close stdin, or both."""
    model_config = ConfigDict(extra="allow")

    closeStdin: bool | None = None
    deltaBase64: str | None = None
    processId: str

class ConfigBatchWriteParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    edits: list[ConfigEdit]
    expectedVersion: str | None = None
    filePath: str | None = None
    reloadUserConfig: bool | None = None

class ConfigEdit(BaseModel):
    model_config = ConfigDict(extra="allow")

    keyPath: str
    mergeStrategy: MergeStrategy
    value: Any

class ConfigReadParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    cwd: str | None = None
    includeLayers: bool = False

class ConfigValueWriteParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    expectedVersion: str | None = None
    filePath: str | None = None
    keyPath: str
    mergeStrategy: MergeStrategy
    value: Any

class DynamicToolSpec(BaseModel):
    model_config = ConfigDict(extra="allow")

    deferLoading: bool | None = None
    description: str
    inputSchema: Any
    name: str

class ExperimentalFeatureEnablementSetParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    enablement: dict[str, bool]

class ExperimentalFeatureListParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    cursor: str | None = None
    limit: int | None = None

class ExternalAgentConfigDetectParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    cwds: list[Any] | None = None
    includeHome: bool | None = None

class ExternalAgentConfigImportParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    migrationItems: list[ExternalAgentConfigMigrationItem]

class ExternalAgentConfigMigrationItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    cwd: str | None = None
    description: str
    itemType: ExternalAgentConfigMigrationItemType

class FeedbackUploadParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    classification: str
    extraLogFiles: list[Any] | None = None
    includeLogs: bool
    reason: str | None = None
    threadId: str | None = None

class FsCopyParams(BaseModel):
    """Copy a file or directory tree on the host filesystem."""
    model_config = ConfigDict(extra="allow")

    destinationPath: AbsolutePathBuf
    recursive: bool | None = None
    sourcePath: AbsolutePathBuf

class FsCreateDirectoryParams(BaseModel):
    """Create a directory on the host filesystem."""
    model_config = ConfigDict(extra="allow")

    path: AbsolutePathBuf
    recursive: bool | None = None

class FsGetMetadataParams(BaseModel):
    """Request metadata for an absolute path."""
    model_config = ConfigDict(extra="allow")

    path: AbsolutePathBuf

class FsReadDirectoryParams(BaseModel):
    """List direct child names for a directory."""
    model_config = ConfigDict(extra="allow")

    path: AbsolutePathBuf

class FsReadFileParams(BaseModel):
    """Read a file from the host filesystem."""
    model_config = ConfigDict(extra="allow")

    path: AbsolutePathBuf

class FsRemoveParams(BaseModel):
    """Remove a file or directory tree from the host filesystem."""
    model_config = ConfigDict(extra="allow")

    force: bool | None = None
    path: AbsolutePathBuf
    recursive: bool | None = None

class FsUnwatchParams(BaseModel):
    """Stop filesystem watch notifications for a prior `fs/watch`."""
    model_config = ConfigDict(extra="allow")

    watchId: str

class FsWatchParams(BaseModel):
    """Start filesystem watch notifications for an absolute path."""
    model_config = ConfigDict(extra="allow")

    path: AbsolutePathBuf

class FsWriteFileParams(BaseModel):
    """Write a file on the host filesystem."""
    model_config = ConfigDict(extra="allow")

    dataBase64: str
    path: AbsolutePathBuf

class FuzzyFileSearchParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    cancellationToken: str | None = None
    query: str
    roots: list[str]

class TurnSteerParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    expectedTurnId: str
    input: list[UserInput]
    threadId: str

class GetAccountParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    refreshToken: bool = False

class GhostCommit(BaseModel):
    """Details of a ghost commit created from a repository state."""
    model_config = ConfigDict(extra="allow")

    id: str
    parent: str | None = None
    preexisting_untracked_dirs: list[str]
    preexisting_untracked_files: list[str]

class InitializeCapabilities(BaseModel):
    """Client-declared capabilities negotiated during initialize."""
    model_config = ConfigDict(extra="allow")

    experimentalApi: bool = False
    optOutNotificationMethods: list[Any] | None = None

class InitializeParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    capabilities: InitializeCapabilities | None = None
    clientInfo: ClientInfo

class ListMcpServerStatusParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    cursor: str | None = None
    limit: int | None = None

class McpServerOauthLoginParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    scopes: list[Any] | None = None
    timeoutSecs: int | None = None

class TurnStartParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = None
    threadId: str
    cwd: str | None = None
    effort: ReasoningEffort | None = None
    input: list[UserInput]
    model: str | None = None
    outputSchema: Any | None = None
    personality: Personality | None = None
    sandboxPolicy: SandboxPolicy | None = None
    serviceTier: ServiceTier | None = None
    summary: ReasoningSummary | None = None

class ModelListParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    cursor: str | None = None
    includeHidden: bool | None = None
    limit: int | None = None

class PluginInstallParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    forceRemoteSync: bool | None = None
    marketplacePath: AbsolutePathBuf
    pluginName: str

class PluginListParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    cwds: list[Any] | None = None
    forceRemoteSync: bool | None = None

class PluginReadParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    marketplacePath: AbsolutePathBuf
    pluginName: str

class PluginUninstallParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    forceRemoteSync: bool | None = None
    pluginId: str

class ReviewStartParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    delivery: ReviewDelivery | None = None
    target: ReviewTarget
    threadId: str

class Settings(BaseModel):
    """Settings for a collaboration mode."""
    model_config = ConfigDict(extra="allow")

    developer_instructions: str | None = None
    model: str
    reasoning_effort: ReasoningEffort | None = None

class SkillsConfigWriteParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    enabled: bool
    name: str | None = None
    path: AbsolutePathBuf | None = None

class SkillsListExtraRootsForCwd(BaseModel):
    model_config = ConfigDict(extra="allow")

    cwd: str
    extraUserRoots: list[str]

class SkillsListParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    cwds: list[str] | None = None
    forceReload: bool | None = None
    perCwdExtraUserRoots: list[Any] | None = None

class TextElement(BaseModel):
    model_config = ConfigDict(extra="allow")

    byteRange: ByteRange
    placeholder: str | None = None

class ThreadArchiveParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    threadId: str

class TurnInterruptParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    threadId: str
    turnId: str

class ThreadCompactStartParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    threadId: str

class ThreadUnsubscribeParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    threadId: str

class ThreadForkParams(BaseModel):
    """There are two ways to fork a thread: 1. By thread_id: load the thread from disk by thread_id and fork it into a new thread. 2. By path: load the thread from disk by path and fork it into a new thread.

If using path, the thread_id param will be ignored.

Prefer using thread_id whenever possible."""
    model_config = ConfigDict(extra="allow")

    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = None
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    ephemeral: bool | None = None
    model: str | None = None
    modelProvider: str | None = None
    serviceTier: ServiceTier | None = None
    threadId: str
    sandbox: SandboxMode | None = None

class ThreadUnarchiveParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    threadId: str

class ThreadListParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    archived: bool | None = None
    cursor: str | None = None
    cwd: str | None = None
    limit: int | None = None
    modelProviders: list[Any] | None = None
    searchTerm: str | None = None
    sortKey: ThreadSortKey | None = None
    sourceKinds: list[Any] | None = None

class ThreadLoadedListParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    cursor: str | None = None
    limit: int | None = None

class ThreadMetadataGitInfoUpdateParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    branch: str | None = None
    originUrl: str | None = None
    sha: str | None = None

class ThreadMetadataUpdateParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    gitInfo: ThreadMetadataGitInfoUpdateParams | None = None
    threadId: str

class ThreadReadParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    includeTurns: bool = False
    threadId: str

class ThreadStartParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = None
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    serviceName: str | None = None
    ephemeral: bool | None = None
    personality: Personality | None = None
    sandbox: SandboxMode | None = None
    model: str | None = None
    modelProvider: str | None = None
    serviceTier: ServiceTier | None = None

class ThreadRealtimeAudioChunk(BaseModel):
    """EXPERIMENTAL - thread realtime audio chunk."""
    model_config = ConfigDict(extra="allow")

    data: str
    itemId: str | None = None
    numChannels: int
    sampleRate: int
    samplesPerChannel: int | None = None

class ThreadShellCommandParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    threadId: str

class ThreadResumeParams(BaseModel):
    """There are three ways to resume a thread: 1. By thread_id: load the thread from disk by thread_id and resume it. 2. By history: instantiate the thread from memory and resume it. 3. By path: load the thread from disk by path and resume it.

The precedence is: history > path > thread_id. If using history or path, the thread_id param will be ignored.

Prefer using thread_id whenever possible."""
    model_config = ConfigDict(extra="allow")

    approvalPolicy: AskForApproval | None = None
    approvalsReviewer: ApprovalsReviewer | None = None
    baseInstructions: str | None = None
    config: dict[str, Any] | None = None
    cwd: str | None = None
    developerInstructions: str | None = None
    serviceTier: ServiceTier | None = None
    model: str | None = None
    modelProvider: str | None = None
    threadId: str
    sandbox: SandboxMode | None = None
    personality: Personality | None = None

class ThreadRollbackParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    numTurns: int
    threadId: str

class ThreadSetNameParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    threadId: str

class GranularAskForApproval(BaseModel):
    model_config = ConfigDict(extra="forbid")

    granular: GranularAskForApprovalGranular

class InputTextContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["input_text"]

class InputImageContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    image_url: str
    type: Literal["input_image"]

class OutputTextContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["output_text"]

class InputTextFunctionCallOutputContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["input_text"]

class InputImageFunctionCallOutputContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    detail: ImageDetail | None = None
    image_url: str
    type: Literal["input_image"]

class TextUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    text_elements: list[TextElement] = []
    type: Literal["text"]

class ImageUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["image"]
    url: str

class LocalImageUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    path: str
    type: Literal["localImage"]

class SkillUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    path: str
    type: Literal["skill"]

class MentionUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    path: str
    type: Literal["mention"]

class ExecLocalShellAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: list[str]
    env: dict[str, Any] | None = None
    timeout_ms: int | None = None
    type: Literal["exec"]
    user: str | None = None
    working_directory: str | None = None

class ApiKeyLoginAccountParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    apiKey: str
    type: Literal["apiKey"]

class ChatgptLoginAccountParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["chatgpt"]

class ChatgptDeviceCodeLoginAccountParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["chatgptDeviceCode"]

class ChatgptAuthTokensLoginAccountParams(BaseModel):
    """[UNSTABLE] FOR OPENAI INTERNAL USE ONLY - DO NOT USE. The access token must contain the same scopes that Codex-managed ChatGPT auth tokens have."""
    model_config = ConfigDict(extra="allow")

    accessToken: str
    chatgptAccountId: str
    chatgptPlanType: str | None = None
    type: Literal["chatgptAuthTokens"]

class RestrictedReadOnlyAccess(BaseModel):
    model_config = ConfigDict(extra="allow")

    includePlatformDefaults: bool = True
    readableRoots: list[AbsolutePathBuf] = []
    type: Literal["restricted"]

class FullAccessReadOnlyAccess(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["fullAccess"]

class ReasoningTextReasoningItemContent(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["reasoning_text"]

class TextReasoningItemContent(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["text"]

class SummaryTextReasoningItemReasoningSummary(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["summary_text"]

class MessageResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    content: list[ContentItem]
    end_turn: bool | None = None
    id: str | None = None
    phase: MessagePhase | None = None
    role: str
    type: Literal["message"]

class ReasoningResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    content: list[Any] | None = None
    encrypted_content: str | None = None
    summary: list[ReasoningItemReasoningSummary]
    type: Literal["reasoning"]

class LocalShellCallResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    action: LocalShellAction
    call_id: str | None = None
    id: str | None = None
    status: LocalShellStatus
    type: Literal["local_shell_call"]

class FunctionCallResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    arguments: str
    call_id: str
    id: str | None = None
    name: str
    namespace: str | None = None
    type: Literal["function_call"]

class ToolSearchCallResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    arguments: Any
    call_id: str | None = None
    execution: str
    id: str | None = None
    status: str | None = None
    type: Literal["tool_search_call"]

class FunctionCallOutputResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    call_id: str
    output: FunctionCallOutputBody
    type: Literal["function_call_output"]

class CustomToolCallResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    call_id: str
    id: str | None = None
    input: str
    name: str
    status: str | None = None
    type: Literal["custom_tool_call"]

class CustomToolCallOutputResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    call_id: str
    name: str | None = None
    output: FunctionCallOutputBody
    type: Literal["custom_tool_call_output"]

class ToolSearchOutputResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    call_id: str | None = None
    execution: str
    status: str
    tools: list[Any]
    type: Literal["tool_search_output"]

class WebSearchCallResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    action: ResponsesApiWebSearchAction | None = None
    id: str | None = None
    status: str | None = None
    type: Literal["web_search_call"]

class ImageGenerationCallResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    result: str
    revised_prompt: str | None = None
    status: str
    type: Literal["image_generation_call"]

class GhostSnapshotResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    ghost_commit: GhostCommit
    type: Literal["ghost_snapshot"]

class CompactionResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    encrypted_content: str
    type: Literal["compaction"]

class OtherResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["other"]

class SearchResponsesApiWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    queries: list[Any] | None = None
    query: str | None = None
    type: Literal["search"]

class OpenPageResponsesApiWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["open_page"]
    url: str | None = None

class FindInPageResponsesApiWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    pattern: str | None = None
    type: Literal["find_in_page"]
    url: str | None = None

class OtherResponsesApiWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["other"]

class UncommittedChangesReviewTarget(BaseModel):
    """Review the working tree: staged, unstaged, and untracked files."""
    model_config = ConfigDict(extra="allow")

    type: Literal["uncommittedChanges"]

class BaseBranchReviewTarget(BaseModel):
    """Review changes between the current branch and the given base branch."""
    model_config = ConfigDict(extra="allow")

    branch: str
    type: Literal["baseBranch"]

class CommitReviewTarget(BaseModel):
    """Review the changes introduced by a specific commit."""
    model_config = ConfigDict(extra="allow")

    sha: str
    title: str | None = None
    type: Literal["commit"]

class CustomReviewTarget(BaseModel):
    """Arbitrary instructions, equivalent to the old free-form prompt."""
    model_config = ConfigDict(extra="allow")

    instructions: str
    type: Literal["custom"]

class DangerFullAccessSandboxPolicy(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["dangerFullAccess"]

class ReadOnlySandboxPolicy(BaseModel):
    model_config = ConfigDict(extra="allow")

    access: ReadOnlyAccess = {"type": "fullAccess"}
    networkAccess: bool = False
    type: Literal["readOnly"]

class ExternalSandboxSandboxPolicy(BaseModel):
    model_config = ConfigDict(extra="allow")

    networkAccess: NetworkAccess = "restricted"
    type: Literal["externalSandbox"]

class WorkspaceWriteSandboxPolicy(BaseModel):
    model_config = ConfigDict(extra="allow")

    excludeSlashTmp: bool = False
    excludeTmpdirEnvVar: bool = False
    networkAccess: bool = False
    readOnlyAccess: ReadOnlyAccess = {"type": "fullAccess"}
    type: Literal["workspaceWrite"]
    writableRoots: list[AbsolutePathBuf] = []

class InitializeRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["initialize"]
    params: InitializeParams

class ThreadStartRequest(BaseModel):
    """NEW APIs"""
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["thread/start"]
    params: ThreadStartParams

class ThreadResumeRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["thread/resume"]
    params: ThreadResumeParams

class ThreadForkRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["thread/fork"]
    params: ThreadForkParams

class ThreadArchiveRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["thread/archive"]
    params: ThreadArchiveParams

class ThreadUnsubscribeRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["thread/unsubscribe"]
    params: ThreadUnsubscribeParams

class ThreadNameSetRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["thread/name/set"]
    params: ThreadSetNameParams

class ThreadMetadataUpdateRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["thread/metadata/update"]
    params: ThreadMetadataUpdateParams

class ThreadUnarchiveRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["thread/unarchive"]
    params: ThreadUnarchiveParams

class ThreadCompactStartRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["thread/compact/start"]
    params: ThreadCompactStartParams

class ThreadShellCommandRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["thread/shellCommand"]
    params: ThreadShellCommandParams

class ThreadRollbackRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["thread/rollback"]
    params: ThreadRollbackParams

class ThreadListRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["thread/list"]
    params: ThreadListParams

class ThreadLoadedListRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["thread/loaded/list"]
    params: ThreadLoadedListParams

class ThreadReadRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["thread/read"]
    params: ThreadReadParams

class SkillsListRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["skills/list"]
    params: SkillsListParams

class PluginListRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["plugin/list"]
    params: PluginListParams

class PluginReadRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["plugin/read"]
    params: PluginReadParams

class AppListRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["app/list"]
    params: AppsListParams

class FsReadFileRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["fs/readFile"]
    params: FsReadFileParams

class FsWriteFileRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["fs/writeFile"]
    params: FsWriteFileParams

class FsCreateDirectoryRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["fs/createDirectory"]
    params: FsCreateDirectoryParams

class FsGetMetadataRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["fs/getMetadata"]
    params: FsGetMetadataParams

class FsReadDirectoryRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["fs/readDirectory"]
    params: FsReadDirectoryParams

class FsRemoveRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["fs/remove"]
    params: FsRemoveParams

class FsCopyRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["fs/copy"]
    params: FsCopyParams

class FsWatchRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["fs/watch"]
    params: FsWatchParams

class FsUnwatchRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["fs/unwatch"]
    params: FsUnwatchParams

class SkillsConfigWriteRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["skills/config/write"]
    params: SkillsConfigWriteParams

class PluginInstallRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["plugin/install"]
    params: PluginInstallParams

class PluginUninstallRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["plugin/uninstall"]
    params: PluginUninstallParams

class TurnStartRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["turn/start"]
    params: TurnStartParams

class TurnSteerRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["turn/steer"]
    params: TurnSteerParams

class TurnInterruptRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["turn/interrupt"]
    params: TurnInterruptParams

class ReviewStartRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["review/start"]
    params: ReviewStartParams

class ModelListRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["model/list"]
    params: ModelListParams

class ExperimentalFeatureListRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["experimentalFeature/list"]
    params: ExperimentalFeatureListParams

class ExperimentalFeatureEnablementSetRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["experimentalFeature/enablement/set"]
    params: ExperimentalFeatureEnablementSetParams

class McpServerOauthLoginRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["mcpServer/oauth/login"]
    params: McpServerOauthLoginParams

class ConfigMcpServerReloadRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["config/mcpServer/reload"]
    params: None = None

class McpServerStatusListRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["mcpServerStatus/list"]
    params: ListMcpServerStatusParams

class WindowsSandboxSetupStartRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["windowsSandbox/setupStart"]
    params: WindowsSandboxSetupStartParams

class AccountLoginStartRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["account/login/start"]
    params: LoginAccountParams

class AccountLoginCancelRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["account/login/cancel"]
    params: CancelLoginAccountParams

class AccountLogoutRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["account/logout"]
    params: None = None

class AccountRateLimitsReadRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["account/rateLimits/read"]
    params: None = None

class FeedbackUploadRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["feedback/upload"]
    params: FeedbackUploadParams

class CommandExecRequest(BaseModel):
    """Execute a standalone command (argv vector) under the server's sandbox."""
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["command/exec"]
    params: CommandExecParams

class CommandExecWriteRequest(BaseModel):
    """Write stdin bytes to a running `command/exec` session or close stdin."""
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["command/exec/write"]
    params: CommandExecWriteParams

class CommandExecTerminateRequest(BaseModel):
    """Terminate a running `command/exec` session by client-supplied `processId`."""
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["command/exec/terminate"]
    params: CommandExecTerminateParams

class CommandExecResizeRequest(BaseModel):
    """Resize a running PTY-backed `command/exec` session by client-supplied `processId`."""
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["command/exec/resize"]
    params: CommandExecResizeParams

class ConfigReadRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["config/read"]
    params: ConfigReadParams

class ExternalAgentConfigDetectRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["externalAgentConfig/detect"]
    params: ExternalAgentConfigDetectParams

class ExternalAgentConfigImportRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["externalAgentConfig/import"]
    params: ExternalAgentConfigImportParams

class ConfigValueWriteRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["config/value/write"]
    params: ConfigValueWriteParams

class ConfigBatchWriteRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["config/batchWrite"]
    params: ConfigBatchWriteParams

class ConfigRequirementsReadRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["configRequirements/read"]
    params: None = None

class AccountReadRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["account/read"]
    params: GetAccountParams

class FuzzyFileSearchRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["fuzzyFileSearch"]
    params: FuzzyFileSearchParams

class GranularAskForApprovalGranular(BaseModel):
    model_config = ConfigDict(extra="allow")

    mcp_elicitations: bool
    request_permissions: bool = False
    rules: bool
    sandbox_approval: bool
    skill_approval: bool = False

AbsolutePathBuf: TypeAlias = str

ApprovalsReviewer: TypeAlias = Literal["user", "guardian_subagent"]

AskForApproval: TypeAlias = Literal["untrusted", "on-failure", "on-request", "never"] | GranularAskForApproval

ContentItem: TypeAlias = InputTextContentItem | InputImageContentItem | OutputTextContentItem

ExternalAgentConfigMigrationItemType: TypeAlias = Literal["AGENTS_MD", "CONFIG", "SKILLS", "MCP_SERVER_CONFIG"]

FunctionCallOutputContentItem: TypeAlias = InputTextFunctionCallOutputContentItem | InputImageFunctionCallOutputContentItem

FunctionCallOutputBody: TypeAlias = str | list[FunctionCallOutputContentItem]

ImageDetail: TypeAlias = Literal["auto", "low", "high", "original"]

LocalShellAction: TypeAlias = ExecLocalShellAction

LocalShellStatus: TypeAlias = Literal["completed", "in_progress", "incomplete"]

LoginAccountParams: TypeAlias = ApiKeyLoginAccountParams | ChatgptLoginAccountParams | ChatgptDeviceCodeLoginAccountParams | ChatgptAuthTokensLoginAccountParams

MergeStrategy: TypeAlias = Literal["replace", "upsert"]

MessagePhase: TypeAlias = Literal["commentary", "final_answer"]

ModeKind: TypeAlias = Literal["plan", "default"]

NetworkAccess: TypeAlias = Literal["restricted", "enabled"]

Personality: TypeAlias = Literal["none", "friendly", "pragmatic"]

ReadOnlyAccess: TypeAlias = RestrictedReadOnlyAccess | FullAccessReadOnlyAccess

ReasoningEffort: TypeAlias = Literal["none", "minimal", "low", "medium", "high", "xhigh"]

ReasoningItemContent: TypeAlias = ReasoningTextReasoningItemContent | TextReasoningItemContent

ReasoningItemReasoningSummary: TypeAlias = SummaryTextReasoningItemReasoningSummary

ReasoningSummary: TypeAlias = Literal["auto", "concise", "detailed", "none"]

RequestId: TypeAlias = str | int

ResponseItem: TypeAlias = MessageResponseItem | ReasoningResponseItem | LocalShellCallResponseItem | FunctionCallResponseItem | ToolSearchCallResponseItem | FunctionCallOutputResponseItem | CustomToolCallResponseItem | CustomToolCallOutputResponseItem | ToolSearchOutputResponseItem | WebSearchCallResponseItem | ImageGenerationCallResponseItem | GhostSnapshotResponseItem | CompactionResponseItem | OtherResponseItem

ResponsesApiWebSearchAction: TypeAlias = SearchResponsesApiWebSearchAction | OpenPageResponsesApiWebSearchAction | FindInPageResponsesApiWebSearchAction | OtherResponsesApiWebSearchAction

ReviewDelivery: TypeAlias = Literal["inline", "detached"]

ReviewTarget: TypeAlias = UncommittedChangesReviewTarget | BaseBranchReviewTarget | CommitReviewTarget | CustomReviewTarget

SandboxMode: TypeAlias = Literal["read-only", "workspace-write", "danger-full-access"]

SandboxPolicy: TypeAlias = DangerFullAccessSandboxPolicy | ReadOnlySandboxPolicy | ExternalSandboxSandboxPolicy | WorkspaceWriteSandboxPolicy

ServiceTier: TypeAlias = Literal["fast", "flex"]

ThreadSortKey: TypeAlias = Literal["created_at", "updated_at"]

ThreadSourceKind: TypeAlias = Literal["cli", "vscode", "exec", "appServer", "subAgent", "subAgentReview", "subAgentCompact", "subAgentThreadSpawn", "subAgentOther", "unknown"]

UserInput: TypeAlias = TextUserInput | ImageUserInput | LocalImageUserInput | SkillUserInput | MentionUserInput

WindowsSandboxSetupMode: TypeAlias = Literal["elevated", "unelevated"]

ClientRequest: TypeAlias = InitializeRequest | ThreadStartRequest | ThreadResumeRequest | ThreadForkRequest | ThreadArchiveRequest | ThreadUnsubscribeRequest | ThreadNameSetRequest | ThreadMetadataUpdateRequest | ThreadUnarchiveRequest | ThreadCompactStartRequest | ThreadShellCommandRequest | ThreadRollbackRequest | ThreadListRequest | ThreadLoadedListRequest | ThreadReadRequest | SkillsListRequest | PluginListRequest | PluginReadRequest | AppListRequest | FsReadFileRequest | FsWriteFileRequest | FsCreateDirectoryRequest | FsGetMetadataRequest | FsReadDirectoryRequest | FsRemoveRequest | FsCopyRequest | FsWatchRequest | FsUnwatchRequest | SkillsConfigWriteRequest | PluginInstallRequest | PluginUninstallRequest | TurnStartRequest | TurnSteerRequest | TurnInterruptRequest | ReviewStartRequest | ModelListRequest | ExperimentalFeatureListRequest | ExperimentalFeatureEnablementSetRequest | McpServerOauthLoginRequest | ConfigMcpServerReloadRequest | McpServerStatusListRequest | WindowsSandboxSetupStartRequest | AccountLoginStartRequest | AccountLoginCancelRequest | AccountLogoutRequest | AccountRateLimitsReadRequest | FeedbackUploadRequest | CommandExecRequest | CommandExecWriteRequest | CommandExecTerminateRequest | CommandExecResizeRequest | ConfigReadRequest | ExternalAgentConfigDetectRequest | ExternalAgentConfigImportRequest | ConfigValueWriteRequest | ConfigBatchWriteRequest | ConfigRequirementsReadRequest | AccountReadRequest | FuzzyFileSearchRequest
