# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class NetworkPolicyAmendment(BaseModel):
    model_config = ConfigDict(extra="allow")

    action: NetworkPolicyRuleAction
    host: str

class AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecision(BaseModel):
    """User approved the command, and wants to apply the proposed execpolicy amendment so future matching commands can run without prompting."""
    model_config = ConfigDict(extra="forbid")

    acceptWithExecpolicyAmendment: AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecisionAcceptWithExecpolicyAmendment

class ApplyNetworkPolicyAmendmentCommandExecutionApprovalDecision(BaseModel):
    """User chose a persistent network policy rule (allow/deny) for this host."""
    model_config = ConfigDict(extra="forbid")

    applyNetworkPolicyAmendment: ApplyNetworkPolicyAmendmentCommandExecutionApprovalDecisionApplyNetworkPolicyAmendment

class AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecisionAcceptWithExecpolicyAmendment(BaseModel):
    model_config = ConfigDict(extra="allow")

    execpolicy_amendment: list[str]

class ApplyNetworkPolicyAmendmentCommandExecutionApprovalDecisionApplyNetworkPolicyAmendment(BaseModel):
    model_config = ConfigDict(extra="allow")

    network_policy_amendment: NetworkPolicyAmendment

CommandExecutionApprovalDecision: TypeAlias = Literal["accept", "acceptForSession", "decline", "cancel"] | AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecision | ApplyNetworkPolicyAmendmentCommandExecutionApprovalDecision

NetworkPolicyRuleAction: TypeAlias = Literal["allow", "deny"]

class CommandExecutionRequestApprovalResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    decision: CommandExecutionApprovalDecision
