# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class AdditionalFileSystemPermissions(BaseModel):
    model_config = ConfigDict(extra="allow")

    read: list[Any] | None = None
    write: list[Any] | None = None

class AdditionalNetworkPermissions(BaseModel):
    model_config = ConfigDict(extra="allow")

    enabled: bool | None = None

class AdditionalPermissionProfile(BaseModel):
    model_config = ConfigDict(extra="allow")

    fileSystem: AdditionalFileSystemPermissions | None = None
    network: AdditionalNetworkPermissions | None = None

class NetworkApprovalContext(BaseModel):
    model_config = ConfigDict(extra="allow")

    host: str
    protocol: NetworkApprovalProtocol

class NetworkPolicyAmendment(BaseModel):
    model_config = ConfigDict(extra="allow")

    action: NetworkPolicyRuleAction
    host: str

class ReadCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    name: str
    path: str
    type: Literal["read"]

class ListFilesCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    path: str | None = None
    type: Literal["listFiles"]

class SearchCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    path: str | None = None
    query: str | None = None
    type: Literal["search"]

class UnknownCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    type: Literal["unknown"]

class AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecision(BaseModel):
    """User approved the command, and wants to apply the proposed execpolicy amendment so future matching commands can run without prompting."""
    model_config = ConfigDict(extra="forbid")

    acceptWithExecpolicyAmendment: AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecisionAcceptWithExecpolicyAmendment

class ApplyNetworkPolicyAmendmentCommandExecutionApprovalDecision(BaseModel):
    """User chose a persistent network policy rule (allow/deny) for this host."""
    model_config = ConfigDict(extra="forbid")

    applyNetworkPolicyAmendment: ApplyNetworkPolicyAmendmentCommandExecutionApprovalDecisionApplyNetworkPolicyAmendment

class AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecisionAcceptWithExecpolicyAmendment(BaseModel):
    model_config = ConfigDict(extra="allow")

    execpolicy_amendment: list[str]

class ApplyNetworkPolicyAmendmentCommandExecutionApprovalDecisionApplyNetworkPolicyAmendment(BaseModel):
    model_config = ConfigDict(extra="allow")

    network_policy_amendment: NetworkPolicyAmendment

AbsolutePathBuf: TypeAlias = str

CommandAction: TypeAlias = ReadCommandAction | ListFilesCommandAction | SearchCommandAction | UnknownCommandAction

CommandExecutionApprovalDecision: TypeAlias = Literal["accept", "acceptForSession", "decline", "cancel"] | AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecision | ApplyNetworkPolicyAmendmentCommandExecutionApprovalDecision

NetworkApprovalProtocol: TypeAlias = Literal["http", "https", "socks5Tcp", "socks5Udp"]

NetworkPolicyRuleAction: TypeAlias = Literal["allow", "deny"]

class CommandExecutionRequestApprovalParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    turnId: str
    approvalId: str | None = None
    threadId: str
    command: str | None = None
    commandActions: list[Any] | None = None
    cwd: str | None = None
    itemId: str
    networkApprovalContext: NetworkApprovalContext | None = None
    proposedExecpolicyAmendment: list[Any] | None = None
    proposedNetworkPolicyAmendments: list[Any] | None = None
    reason: str | None = None
