# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class InputTextDynamicToolCallOutputContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["inputText"]

class InputImageDynamicToolCallOutputContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    imageUrl: str
    type: Literal["inputImage"]

DynamicToolCallOutputContentItem: TypeAlias = InputTextDynamicToolCallOutputContentItem | InputImageDynamicToolCallOutputContentItem

class DynamicToolCallResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    contentItems: list[DynamicToolCallOutputContentItem]
    success: bool
