# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class ReadParsedCommand(BaseModel):
    model_config = ConfigDict(extra="allow")

    cmd: str
    name: str
    path: str
    type: Literal["read"]

class ListFilesParsedCommand(BaseModel):
    model_config = ConfigDict(extra="allow")

    cmd: str
    path: str | None = None
    type: Literal["list_files"]

class SearchParsedCommand(BaseModel):
    model_config = ConfigDict(extra="allow")

    cmd: str
    path: str | None = None
    query: str | None = None
    type: Literal["search"]

class UnknownParsedCommand(BaseModel):
    model_config = ConfigDict(extra="allow")

    cmd: str
    type: Literal["unknown"]

ParsedCommand: TypeAlias = ReadParsedCommand | ListFilesParsedCommand | SearchParsedCommand | UnknownParsedCommand

ThreadId: TypeAlias = str

class ExecCommandApprovalParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    approvalId: str | None = None
    callId: str
    command: list[str]
    conversationId: ThreadId
    cwd: str
    parsedCmd: list[ParsedCommand]
    reason: str | None = None
