# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class NetworkPolicyAmendment(BaseModel):
    model_config = ConfigDict(extra="allow")

    action: NetworkPolicyRuleAction
    host: str

class ApprovedExecpolicyAmendmentReviewDecision(BaseModel):
    """User has approved this command and wants to apply the proposed execpolicy amendment so future matching commands are permitted."""
    model_config = ConfigDict(extra="forbid")

    approved_execpolicy_amendment: ApprovedExecpolicyAmendmentReviewDecisionApprovedExecpolicyAmendment

class NetworkPolicyAmendmentReviewDecision(BaseModel):
    """User chose to persist a network policy rule (allow/deny) for future requests to the same host."""
    model_config = ConfigDict(extra="forbid")

    network_policy_amendment: NetworkPolicyAmendmentReviewDecisionNetworkPolicyAmendment

class ApprovedExecpolicyAmendmentReviewDecisionApprovedExecpolicyAmendment(BaseModel):
    model_config = ConfigDict(extra="allow")

    proposed_execpolicy_amendment: list[str]

class NetworkPolicyAmendmentReviewDecisionNetworkPolicyAmendment(BaseModel):
    model_config = ConfigDict(extra="allow")

    network_policy_amendment: NetworkPolicyAmendment

NetworkPolicyRuleAction: TypeAlias = Literal["allow", "deny"]

ReviewDecision: TypeAlias = Literal["approved", "approved_for_session", "denied", "abort"] | ApprovedExecpolicyAmendmentReviewDecision | NetworkPolicyAmendmentReviewDecision

class ExecCommandApprovalResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    decision: ReviewDecision
