# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class FuzzyFileSearchResult(BaseModel):
    """Superset of [`codex_file_search::FileMatch`]"""
    model_config = ConfigDict(extra="allow")

    file_name: str
    indices: list[Any] | None = None
    match_type: FuzzyFileSearchMatchType
    path: str
    root: str
    score: int

FuzzyFileSearchMatchType: TypeAlias = Literal["file", "directory"]

class FuzzyFileSearchSessionUpdatedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    files: list[FuzzyFileSearchResult]
    query: str
    sessionId: str
