# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict


class JsonrpcNotification(BaseModel):
    """A notification which does not expect a response."""
    model_config = ConfigDict(extra="allow")

    method: str
    params: Any | None = None
