# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, TypeAlias

from pydantic import BaseModel, ConfigDict


class W3CTraceContext(BaseModel):
    model_config = ConfigDict(extra="allow")

    traceparent: str | None = None
    tracestate: str | None = None

RequestId: TypeAlias = str | int

class JsonrpcRequest(BaseModel):
    """A request that expects a response."""
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: str
    params: Any | None = None
    trace: W3CTraceContext | None = None
