# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict, Field

McpServerElicitationAction: TypeAlias = Literal["accept", "decline", "cancel"]

class McpServerElicitationRequestResponse(BaseModel):
    model_config = ConfigDict(extra="allow")

    meta: Any | None = Field(default=None, alias="_meta")
    action: McpServerElicitationAction
    content: Any | None = None
