# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict, Field


class McpElicitationBooleanSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: bool | None = None
    description: str | None = None
    title: str | None = None
    type: McpElicitationBooleanType

class McpElicitationConstOption(BaseModel):
    model_config = ConfigDict(extra="forbid")

    const: str
    title: str

class McpElicitationLegacyTitledEnumSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: str | None = None
    description: str | None = None
    enum: list[str]
    enumNames: list[Any] | None = None
    title: str | None = None
    type: McpElicitationStringType

class McpElicitationNumberSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: float | None = None
    description: str | None = None
    maximum: float | None = None
    minimum: float | None = None
    title: str | None = None
    type: McpElicitationNumberType

class McpElicitationSchema(BaseModel):
    """Typed form schema for MCP `elicitation/create` requests.

This matches the `requestedSchema` shape from the MCP 2025-11-25 `ElicitRequestFormParams` schema."""
    model_config = ConfigDict(extra="forbid")

    schema_: str | None = Field(default=None, alias="$schema")
    properties: dict[str, McpElicitationPrimitiveSchema]
    required: list[Any] | None = None
    type: McpElicitationObjectType

class McpElicitationStringSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: str | None = None
    description: str | None = None
    format: McpElicitationStringFormat | None = None
    maxLength: int | None = None
    minLength: int | None = None
    title: str | None = None
    type: McpElicitationStringType

class McpElicitationTitledEnumItems(BaseModel):
    model_config = ConfigDict(extra="forbid")

    anyOf: list[McpElicitationConstOption]

class McpElicitationTitledMultiSelectEnumSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: list[Any] | None = None
    description: str | None = None
    items: McpElicitationTitledEnumItems
    maxItems: int | None = None
    minItems: int | None = None
    title: str | None = None
    type: McpElicitationArrayType

class McpElicitationTitledSingleSelectEnumSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: str | None = None
    description: str | None = None
    oneOf: list[McpElicitationConstOption]
    title: str | None = None
    type: McpElicitationStringType

class McpElicitationUntitledEnumItems(BaseModel):
    model_config = ConfigDict(extra="forbid")

    enum: list[str]
    type: McpElicitationStringType

class McpElicitationUntitledMultiSelectEnumSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: list[Any] | None = None
    description: str | None = None
    items: McpElicitationUntitledEnumItems
    maxItems: int | None = None
    minItems: int | None = None
    title: str | None = None
    type: McpElicitationArrayType

class McpElicitationUntitledSingleSelectEnumSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: str | None = None
    description: str | None = None
    enum: list[str]
    title: str | None = None
    type: McpElicitationStringType

McpElicitationArrayType: TypeAlias = Literal["array"]

McpElicitationBooleanType: TypeAlias = Literal["boolean"]

McpElicitationMultiSelectEnumSchema: TypeAlias = McpElicitationUntitledMultiSelectEnumSchema | McpElicitationTitledMultiSelectEnumSchema

McpElicitationSingleSelectEnumSchema: TypeAlias = McpElicitationUntitledSingleSelectEnumSchema | McpElicitationTitledSingleSelectEnumSchema

McpElicitationEnumSchema: TypeAlias = McpElicitationSingleSelectEnumSchema | McpElicitationMultiSelectEnumSchema | McpElicitationLegacyTitledEnumSchema

McpElicitationNumberType: TypeAlias = Literal["number", "integer"]

McpElicitationObjectType: TypeAlias = Literal["object"]

McpElicitationPrimitiveSchema: TypeAlias = McpElicitationEnumSchema | McpElicitationStringSchema | McpElicitationNumberSchema | McpElicitationBooleanSchema

McpElicitationStringFormat: TypeAlias = Literal["email", "uri", "date", "date-time"]

McpElicitationStringType: TypeAlias = Literal["string"]

class McpServerElicitationRequestParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    serverName: str
    threadId: str
    turnId: str | None = None
