# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, TypeAlias

from pydantic import BaseModel, ConfigDict


class AdditionalFileSystemPermissions(BaseModel):
    model_config = ConfigDict(extra="allow")

    read: list[Any] | None = None
    write: list[Any] | None = None

class AdditionalNetworkPermissions(BaseModel):
    model_config = ConfigDict(extra="allow")

    enabled: bool | None = None

class RequestPermissionProfile(BaseModel):
    model_config = ConfigDict(extra="forbid")

    fileSystem: AdditionalFileSystemPermissions | None = None
    network: AdditionalNetworkPermissions | None = None

AbsolutePathBuf: TypeAlias = str

class PermissionsRequestApprovalParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    itemId: str
    permissions: RequestPermissionProfile
    reason: str | None = None
    threadId: str
    turnId: str
