# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict, Field


class AdditionalFileSystemPermissions(BaseModel):
    model_config = ConfigDict(extra="allow")

    read: list[Any] | None = None
    write: list[Any] | None = None

class AdditionalNetworkPermissions(BaseModel):
    model_config = ConfigDict(extra="allow")

    enabled: bool | None = None

class AdditionalPermissionProfile(BaseModel):
    model_config = ConfigDict(extra="allow")

    fileSystem: AdditionalFileSystemPermissions | None = None
    network: AdditionalNetworkPermissions | None = None

class ApplyPatchApprovalParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    callId: str
    conversationId: ThreadId
    fileChanges: dict[str, FileChange]
    grantRoot: str | None = None
    reason: str | None = None

class ChatgptAuthTokensRefreshParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    previousAccountId: str | None = None
    reason: ChatgptAuthTokensRefreshReason

class CommandExecutionRequestApprovalParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    turnId: str
    approvalId: str | None = None
    threadId: str
    command: str | None = None
    commandActions: list[Any] | None = None
    cwd: str | None = None
    itemId: str
    networkApprovalContext: NetworkApprovalContext | None = None
    proposedExecpolicyAmendment: list[Any] | None = None
    proposedNetworkPolicyAmendments: list[Any] | None = None
    reason: str | None = None

class DynamicToolCallParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    arguments: Any
    callId: str
    threadId: str
    tool: str
    turnId: str

class ExecCommandApprovalParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    approvalId: str | None = None
    callId: str
    command: list[str]
    conversationId: ThreadId
    cwd: str
    parsedCmd: list[ParsedCommand]
    reason: str | None = None

class FileChangeRequestApprovalParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    grantRoot: str | None = None
    itemId: str
    reason: str | None = None
    threadId: str
    turnId: str

class McpElicitationBooleanSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: bool | None = None
    description: str | None = None
    title: str | None = None
    type: McpElicitationBooleanType

class McpElicitationConstOption(BaseModel):
    model_config = ConfigDict(extra="forbid")

    const: str
    title: str

class McpElicitationLegacyTitledEnumSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: str | None = None
    description: str | None = None
    enum: list[str]
    enumNames: list[Any] | None = None
    title: str | None = None
    type: McpElicitationStringType

class McpElicitationNumberSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: float | None = None
    description: str | None = None
    maximum: float | None = None
    minimum: float | None = None
    title: str | None = None
    type: McpElicitationNumberType

class McpElicitationSchema(BaseModel):
    """Typed form schema for MCP `elicitation/create` requests.

This matches the `requestedSchema` shape from the MCP 2025-11-25 `ElicitRequestFormParams` schema."""
    model_config = ConfigDict(extra="forbid")

    schema_: str | None = Field(default=None, alias="$schema")
    properties: dict[str, McpElicitationPrimitiveSchema]
    required: list[Any] | None = None
    type: McpElicitationObjectType

class McpElicitationStringSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: str | None = None
    description: str | None = None
    format: McpElicitationStringFormat | None = None
    maxLength: int | None = None
    minLength: int | None = None
    title: str | None = None
    type: McpElicitationStringType

class McpElicitationTitledEnumItems(BaseModel):
    model_config = ConfigDict(extra="forbid")

    anyOf: list[McpElicitationConstOption]

class McpElicitationTitledMultiSelectEnumSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: list[Any] | None = None
    description: str | None = None
    items: McpElicitationTitledEnumItems
    maxItems: int | None = None
    minItems: int | None = None
    title: str | None = None
    type: McpElicitationArrayType

class McpElicitationTitledSingleSelectEnumSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: str | None = None
    description: str | None = None
    oneOf: list[McpElicitationConstOption]
    title: str | None = None
    type: McpElicitationStringType

class McpElicitationUntitledEnumItems(BaseModel):
    model_config = ConfigDict(extra="forbid")

    enum: list[str]
    type: McpElicitationStringType

class McpElicitationUntitledMultiSelectEnumSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: list[Any] | None = None
    description: str | None = None
    items: McpElicitationUntitledEnumItems
    maxItems: int | None = None
    minItems: int | None = None
    title: str | None = None
    type: McpElicitationArrayType

class McpElicitationUntitledSingleSelectEnumSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")

    default: str | None = None
    description: str | None = None
    enum: list[str]
    title: str | None = None
    type: McpElicitationStringType

class McpServerElicitationRequestParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    serverName: str
    threadId: str
    turnId: str | None = None

class NetworkApprovalContext(BaseModel):
    model_config = ConfigDict(extra="allow")

    host: str
    protocol: NetworkApprovalProtocol

class NetworkPolicyAmendment(BaseModel):
    model_config = ConfigDict(extra="allow")

    action: NetworkPolicyRuleAction
    host: str

class PermissionsRequestApprovalParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    itemId: str
    permissions: RequestPermissionProfile
    reason: str | None = None
    threadId: str
    turnId: str

class RequestPermissionProfile(BaseModel):
    model_config = ConfigDict(extra="forbid")

    fileSystem: AdditionalFileSystemPermissions | None = None
    network: AdditionalNetworkPermissions | None = None

class ToolRequestUserInputOption(BaseModel):
    """EXPERIMENTAL. Defines a single selectable option for request_user_input."""
    model_config = ConfigDict(extra="allow")

    description: str
    label: str

class ToolRequestUserInputParams(BaseModel):
    """EXPERIMENTAL. Params sent with a request_user_input event."""
    model_config = ConfigDict(extra="allow")

    itemId: str
    questions: list[ToolRequestUserInputQuestion]
    threadId: str
    turnId: str

class ToolRequestUserInputQuestion(BaseModel):
    """EXPERIMENTAL. Represents one request_user_input question and its required options."""
    model_config = ConfigDict(extra="allow")

    header: str
    id: str
    isOther: bool = False
    isSecret: bool = False
    options: list[Any] | None = None
    question: str

class ReadCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    name: str
    path: str
    type: Literal["read"]

class ListFilesCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    path: str | None = None
    type: Literal["listFiles"]

class SearchCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    path: str | None = None
    query: str | None = None
    type: Literal["search"]

class UnknownCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    type: Literal["unknown"]

class AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecision(BaseModel):
    """User approved the command, and wants to apply the proposed execpolicy amendment so future matching commands can run without prompting."""
    model_config = ConfigDict(extra="forbid")

    acceptWithExecpolicyAmendment: AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecisionAcceptWithExecpolicyAmendment

class ApplyNetworkPolicyAmendmentCommandExecutionApprovalDecision(BaseModel):
    """User chose a persistent network policy rule (allow/deny) for this host."""
    model_config = ConfigDict(extra="forbid")

    applyNetworkPolicyAmendment: ApplyNetworkPolicyAmendmentCommandExecutionApprovalDecisionApplyNetworkPolicyAmendment

class AddFileChange(BaseModel):
    model_config = ConfigDict(extra="allow")

    content: str
    type: Literal["add"]

class DeleteFileChange(BaseModel):
    model_config = ConfigDict(extra="allow")

    content: str
    type: Literal["delete"]

class UpdateFileChange(BaseModel):
    model_config = ConfigDict(extra="allow")

    move_path: str | None = None
    type: Literal["update"]
    unified_diff: str

class ReadParsedCommand(BaseModel):
    model_config = ConfigDict(extra="allow")

    cmd: str
    name: str
    path: str
    type: Literal["read"]

class ListFilesParsedCommand(BaseModel):
    model_config = ConfigDict(extra="allow")

    cmd: str
    path: str | None = None
    type: Literal["list_files"]

class SearchParsedCommand(BaseModel):
    model_config = ConfigDict(extra="allow")

    cmd: str
    path: str | None = None
    query: str | None = None
    type: Literal["search"]

class UnknownParsedCommand(BaseModel):
    model_config = ConfigDict(extra="allow")

    cmd: str
    type: Literal["unknown"]

class ItemCommandExecutionRequestApprovalRequest(BaseModel):
    """NEW APIs Sent when approval is requested for a specific command execution. This request is used for Turns started via turn/start."""
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["item/commandExecution/requestApproval"]
    params: CommandExecutionRequestApprovalParams

class ItemFileChangeRequestApprovalRequest(BaseModel):
    """Sent when approval is requested for a specific file change. This request is used for Turns started via turn/start."""
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["item/fileChange/requestApproval"]
    params: FileChangeRequestApprovalParams

class ItemToolRequestUserInputRequest(BaseModel):
    """EXPERIMENTAL - Request input from the user for a tool call."""
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["item/tool/requestUserInput"]
    params: ToolRequestUserInputParams

class McpServerElicitationRequestRequest(BaseModel):
    """Request input for an MCP server elicitation."""
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["mcpServer/elicitation/request"]
    params: McpServerElicitationRequestParams

class ItemPermissionsRequestApprovalRequest(BaseModel):
    """Request approval for additional permissions from the user."""
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["item/permissions/requestApproval"]
    params: PermissionsRequestApprovalParams

class ItemToolCallRequest(BaseModel):
    """Execute a dynamic tool call on the client."""
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["item/tool/call"]
    params: DynamicToolCallParams

class AccountChatgptAuthTokensRefreshRequest(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["account/chatgptAuthTokens/refresh"]
    params: ChatgptAuthTokensRefreshParams

class ApplyPatchApprovalRequest(BaseModel):
    """DEPRECATED APIs below Request to approve a patch. This request is used for Turns started via the legacy APIs (i.e. SendUserTurn, SendUserMessage)."""
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["applyPatchApproval"]
    params: ApplyPatchApprovalParams

class ExecCommandApprovalRequest(BaseModel):
    """Request to exec a command. This request is used for Turns started via the legacy APIs (i.e. SendUserTurn, SendUserMessage)."""
    model_config = ConfigDict(extra="allow")

    id: RequestId
    method: Literal["execCommandApproval"]
    params: ExecCommandApprovalParams

class AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecisionAcceptWithExecpolicyAmendment(BaseModel):
    model_config = ConfigDict(extra="allow")

    execpolicy_amendment: list[str]

class ApplyNetworkPolicyAmendmentCommandExecutionApprovalDecisionApplyNetworkPolicyAmendment(BaseModel):
    model_config = ConfigDict(extra="allow")

    network_policy_amendment: NetworkPolicyAmendment

AbsolutePathBuf: TypeAlias = str

ChatgptAuthTokensRefreshReason: TypeAlias = Literal["unauthorized"]

CommandAction: TypeAlias = ReadCommandAction | ListFilesCommandAction | SearchCommandAction | UnknownCommandAction

CommandExecutionApprovalDecision: TypeAlias = Literal["accept", "acceptForSession", "decline", "cancel"] | AcceptWithExecpolicyAmendmentCommandExecutionApprovalDecision | ApplyNetworkPolicyAmendmentCommandExecutionApprovalDecision

FileChange: TypeAlias = AddFileChange | DeleteFileChange | UpdateFileChange

McpElicitationArrayType: TypeAlias = Literal["array"]

McpElicitationBooleanType: TypeAlias = Literal["boolean"]

McpElicitationMultiSelectEnumSchema: TypeAlias = McpElicitationUntitledMultiSelectEnumSchema | McpElicitationTitledMultiSelectEnumSchema

McpElicitationSingleSelectEnumSchema: TypeAlias = McpElicitationUntitledSingleSelectEnumSchema | McpElicitationTitledSingleSelectEnumSchema

McpElicitationEnumSchema: TypeAlias = McpElicitationSingleSelectEnumSchema | McpElicitationMultiSelectEnumSchema | McpElicitationLegacyTitledEnumSchema

McpElicitationNumberType: TypeAlias = Literal["number", "integer"]

McpElicitationObjectType: TypeAlias = Literal["object"]

McpElicitationPrimitiveSchema: TypeAlias = McpElicitationEnumSchema | McpElicitationStringSchema | McpElicitationNumberSchema | McpElicitationBooleanSchema

McpElicitationStringFormat: TypeAlias = Literal["email", "uri", "date", "date-time"]

McpElicitationStringType: TypeAlias = Literal["string"]

NetworkApprovalProtocol: TypeAlias = Literal["http", "https", "socks5Tcp", "socks5Udp"]

NetworkPolicyRuleAction: TypeAlias = Literal["allow", "deny"]

ParsedCommand: TypeAlias = ReadParsedCommand | ListFilesParsedCommand | SearchParsedCommand | UnknownParsedCommand

RequestId: TypeAlias = str | int

ThreadId: TypeAlias = str

ServerRequest: TypeAlias = ItemCommandExecutionRequestApprovalRequest | ItemFileChangeRequestApprovalRequest | ItemToolRequestUserInputRequest | McpServerElicitationRequestRequest | ItemPermissionsRequestApprovalRequest | ItemToolCallRequest | AccountChatgptAuthTokensRefreshRequest | ApplyPatchApprovalRequest | ExecCommandApprovalRequest
