# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict


class AccountLoginCompletedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    error: str | None = None
    loginId: str | None = None
    success: bool

class AccountRateLimitsUpdatedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    rateLimits: RateLimitSnapshot

class AccountUpdatedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    authMode: AuthMode | None = None
    planType: PlanType | None = None

class AgentMessageDeltaNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    delta: str
    itemId: str
    threadId: str
    turnId: str

class AppBranding(BaseModel):
    """EXPERIMENTAL - app metadata returned by app-list APIs."""
    model_config = ConfigDict(extra="allow")

    category: str | None = None
    developer: str | None = None
    isDiscoverableApp: bool
    privacyPolicy: str | None = None
    termsOfService: str | None = None
    website: str | None = None

class AppInfo(BaseModel):
    """EXPERIMENTAL - app metadata returned by app-list APIs."""
    model_config = ConfigDict(extra="allow")

    appMetadata: AppMetadata | None = None
    branding: AppBranding | None = None
    description: str | None = None
    distributionChannel: str | None = None
    id: str
    installUrl: str | None = None
    isAccessible: bool = False
    isEnabled: bool = True
    labels: dict[str, Any] | None = None
    logoUrl: str | None = None
    logoUrlDark: str | None = None
    name: str
    pluginDisplayNames: list[str] = []

class AppListUpdatedNotification(BaseModel):
    """EXPERIMENTAL - notification emitted when the app list changes."""
    model_config = ConfigDict(extra="allow")

    data: list[AppInfo]

class AppMetadata(BaseModel):
    model_config = ConfigDict(extra="allow")

    categories: list[Any] | None = None
    developer: str | None = None
    firstPartyRequiresInstall: bool | None = None
    firstPartyType: str | None = None
    review: AppReview | None = None
    screenshots: list[Any] | None = None
    seoDescription: str | None = None
    showInComposerWhenUnlinked: bool | None = None
    subCategories: list[Any] | None = None
    version: str | None = None
    versionId: str | None = None
    versionNotes: str | None = None

class AppReview(BaseModel):
    model_config = ConfigDict(extra="allow")

    status: str

class AppScreenshot(BaseModel):
    model_config = ConfigDict(extra="allow")

    fileId: str | None = None
    url: str | None = None
    userPrompt: str

class ByteRange(BaseModel):
    model_config = ConfigDict(extra="allow")

    end: int
    start: int

class CollabAgentState(BaseModel):
    model_config = ConfigDict(extra="allow")

    message: str | None = None
    status: CollabAgentStatus

class CommandExecOutputDeltaNotification(BaseModel):
    """Base64-encoded output chunk emitted for a streaming `command/exec` request.

These notifications are connection-scoped. If the originating connection closes, the server terminates the process."""
    model_config = ConfigDict(extra="allow")

    capReached: bool
    deltaBase64: str
    processId: str
    stream: CommandExecOutputStream

class CommandExecutionOutputDeltaNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    delta: str
    itemId: str
    threadId: str
    turnId: str

class ConfigWarningNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    details: str | None = None
    path: str | None = None
    range: TextRange | None = None
    summary: str

class ContextCompactedNotification(BaseModel):
    """Deprecated: Use `ContextCompaction` item type instead."""
    model_config = ConfigDict(extra="allow")

    threadId: str
    turnId: str

class CreditsSnapshot(BaseModel):
    model_config = ConfigDict(extra="allow")

    balance: str | None = None
    hasCredits: bool
    unlimited: bool

class DeprecationNoticeNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    details: str | None = None
    summary: str

class ErrorNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    error: TurnError
    threadId: str
    turnId: str
    willRetry: bool

class FileChangeOutputDeltaNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    delta: str
    itemId: str
    threadId: str
    turnId: str

class FileUpdateChange(BaseModel):
    model_config = ConfigDict(extra="allow")

    diff: str
    kind: PatchChangeKind
    path: str

class FsChangedNotification(BaseModel):
    """Filesystem watch notification emitted for `fs/watch` subscribers."""
    model_config = ConfigDict(extra="allow")

    changedPaths: list[AbsolutePathBuf]
    watchId: str

class FuzzyFileSearchResult(BaseModel):
    """Superset of [`codex_file_search::FileMatch`]"""
    model_config = ConfigDict(extra="allow")

    file_name: str
    indices: list[Any] | None = None
    match_type: FuzzyFileSearchMatchType
    path: str
    root: str
    score: int

class FuzzyFileSearchSessionCompletedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    sessionId: str

class FuzzyFileSearchSessionUpdatedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    files: list[FuzzyFileSearchResult]
    query: str
    sessionId: str

class GitInfo(BaseModel):
    model_config = ConfigDict(extra="allow")

    branch: str | None = None
    originUrl: str | None = None
    sha: str | None = None

class GuardianApprovalReview(BaseModel):
    """[UNSTABLE] Temporary guardian approval review payload used by `item/autoApprovalReview/*` notifications. This shape is expected to change soon."""
    model_config = ConfigDict(extra="allow")

    rationale: str | None = None
    riskLevel: GuardianRiskLevel | None = None
    riskScore: int | None = None
    status: GuardianApprovalReviewStatus

class HookCompletedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    run: HookRunSummary
    threadId: str
    turnId: str | None = None

class HookOutputEntry(BaseModel):
    model_config = ConfigDict(extra="allow")

    kind: HookOutputEntryKind
    text: str

class HookPromptFragment(BaseModel):
    model_config = ConfigDict(extra="allow")

    hookRunId: str
    text: str

class HookRunSummary(BaseModel):
    model_config = ConfigDict(extra="allow")

    completedAt: int | None = None
    displayOrder: int
    durationMs: int | None = None
    entries: list[HookOutputEntry]
    eventName: HookEventName
    executionMode: HookExecutionMode
    handlerType: HookHandlerType
    id: str
    scope: HookScope
    sourcePath: str
    startedAt: int
    status: HookRunStatus
    statusMessage: str | None = None

class HookStartedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    run: HookRunSummary
    threadId: str
    turnId: str | None = None

class ItemCompletedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    item: ThreadItem
    threadId: str
    turnId: str

class ItemGuardianApprovalReviewCompletedNotification(BaseModel):
    """[UNSTABLE] Temporary notification payload for guardian automatic approval review. This shape is expected to change soon.

TODO(ccunningham): Attach guardian review state to the reviewed tool item's lifecycle instead of sending separate standalone review notifications so the app-server API can persist and replay review state via `thread/read`."""
    model_config = ConfigDict(extra="allow")

    action: Any | None = None
    review: GuardianApprovalReview
    targetItemId: str
    threadId: str
    turnId: str

class ItemGuardianApprovalReviewStartedNotification(BaseModel):
    """[UNSTABLE] Temporary notification payload for guardian automatic approval review. This shape is expected to change soon.

TODO(ccunningham): Attach guardian review state to the reviewed tool item's lifecycle instead of sending separate standalone review notifications so the app-server API can persist and replay review state via `thread/read`."""
    model_config = ConfigDict(extra="allow")

    action: Any | None = None
    review: GuardianApprovalReview
    targetItemId: str
    threadId: str
    turnId: str

class ItemStartedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    item: ThreadItem
    threadId: str
    turnId: str

class McpServerOauthLoginCompletedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    error: str | None = None
    name: str
    success: bool

class McpServerStatusUpdatedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    error: str | None = None
    name: str
    status: McpServerStartupState

class McpToolCallError(BaseModel):
    model_config = ConfigDict(extra="allow")

    message: str

class McpToolCallProgressNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    itemId: str
    message: str
    threadId: str
    turnId: str

class McpToolCallResult(BaseModel):
    model_config = ConfigDict(extra="allow")

    content: list[Any]
    structuredContent: Any | None = None

class MemoryCitation(BaseModel):
    model_config = ConfigDict(extra="allow")

    entries: list[MemoryCitationEntry]
    threadIds: list[str]

class MemoryCitationEntry(BaseModel):
    model_config = ConfigDict(extra="allow")

    lineEnd: int
    lineStart: int
    note: str
    path: str

class ModelReroutedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    fromModel: str
    reason: ModelRerouteReason
    threadId: str
    toModel: str
    turnId: str

class PlanDeltaNotification(BaseModel):
    """EXPERIMENTAL - proposed plan streaming deltas for plan items. Clients should not assume concatenated deltas match the completed plan item content."""
    model_config = ConfigDict(extra="allow")

    delta: str
    itemId: str
    threadId: str
    turnId: str

class RateLimitSnapshot(BaseModel):
    model_config = ConfigDict(extra="allow")

    credits: CreditsSnapshot | None = None
    limitId: str | None = None
    limitName: str | None = None
    planType: PlanType | None = None
    primary: RateLimitWindow | None = None
    secondary: RateLimitWindow | None = None

class RateLimitWindow(BaseModel):
    model_config = ConfigDict(extra="allow")

    resetsAt: int | None = None
    usedPercent: int
    windowDurationMins: int | None = None

class ReasoningSummaryPartAddedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    itemId: str
    summaryIndex: int
    threadId: str
    turnId: str

class ReasoningSummaryTextDeltaNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    delta: str
    itemId: str
    summaryIndex: int
    threadId: str
    turnId: str

class ReasoningTextDeltaNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    contentIndex: int
    delta: str
    itemId: str
    threadId: str
    turnId: str

class ServerRequestResolvedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    requestId: RequestId
    threadId: str

class TerminalInteractionNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    itemId: str
    processId: str
    stdin: str
    threadId: str
    turnId: str

class TextElement(BaseModel):
    model_config = ConfigDict(extra="allow")

    byteRange: ByteRange
    placeholder: str | None = None

class TextPosition(BaseModel):
    model_config = ConfigDict(extra="allow")

    column: int
    line: int

class TextRange(BaseModel):
    model_config = ConfigDict(extra="allow")

    end: TextPosition
    start: TextPosition

class Thread(BaseModel):
    model_config = ConfigDict(extra="allow")

    agentNickname: str | None = None
    agentRole: str | None = None
    cliVersion: str
    createdAt: int
    cwd: str
    ephemeral: bool
    gitInfo: GitInfo | None = None
    id: str
    modelProvider: str
    name: str | None = None
    path: str | None = None
    preview: str
    source: SessionSource
    status: ThreadStatus
    turns: list[Turn]
    updatedAt: int

class ThreadArchivedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    threadId: str

class ThreadClosedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    threadId: str

class ThreadNameUpdatedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    threadId: str
    threadName: str | None = None

class ThreadRealtimeAudioChunk(BaseModel):
    """EXPERIMENTAL - thread realtime audio chunk."""
    model_config = ConfigDict(extra="allow")

    data: str
    itemId: str | None = None
    numChannels: int
    sampleRate: int
    samplesPerChannel: int | None = None

class ThreadRealtimeClosedNotification(BaseModel):
    """EXPERIMENTAL - emitted when thread realtime transport closes."""
    model_config = ConfigDict(extra="allow")

    reason: str | None = None
    threadId: str

class ThreadRealtimeErrorNotification(BaseModel):
    """EXPERIMENTAL - emitted when thread realtime encounters an error."""
    model_config = ConfigDict(extra="allow")

    message: str
    threadId: str

class ThreadRealtimeItemAddedNotification(BaseModel):
    """EXPERIMENTAL - raw non-audio thread realtime item emitted by the backend."""
    model_config = ConfigDict(extra="allow")

    item: Any
    threadId: str

class ThreadRealtimeOutputAudioDeltaNotification(BaseModel):
    """EXPERIMENTAL - streamed output audio emitted by thread realtime."""
    model_config = ConfigDict(extra="allow")

    audio: ThreadRealtimeAudioChunk
    threadId: str

class ThreadRealtimeStartedNotification(BaseModel):
    """EXPERIMENTAL - emitted when thread realtime startup is accepted."""
    model_config = ConfigDict(extra="allow")

    sessionId: str | None = None
    threadId: str
    version: RealtimeConversationVersion

class ThreadRealtimeTranscriptUpdatedNotification(BaseModel):
    """EXPERIMENTAL - flat transcript delta emitted whenever realtime transcript text changes."""
    model_config = ConfigDict(extra="allow")

    role: str
    text: str
    threadId: str

class ThreadStartedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    thread: Thread

class ThreadStatusChangedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    status: ThreadStatus
    threadId: str

class ThreadTokenUsage(BaseModel):
    model_config = ConfigDict(extra="allow")

    last: TokenUsageBreakdown
    modelContextWindow: int | None = None
    total: TokenUsageBreakdown

class ThreadTokenUsageUpdatedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    threadId: str
    tokenUsage: ThreadTokenUsage
    turnId: str

class ThreadUnarchivedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    threadId: str

class TokenUsageBreakdown(BaseModel):
    model_config = ConfigDict(extra="allow")

    cachedInputTokens: int
    inputTokens: int
    outputTokens: int
    reasoningOutputTokens: int
    totalTokens: int

class Turn(BaseModel):
    model_config = ConfigDict(extra="allow")

    error: TurnError | None = None
    id: str
    items: list[ThreadItem]
    status: TurnStatus

class TurnCompletedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    threadId: str
    turn: Turn

class TurnDiffUpdatedNotification(BaseModel):
    """Notification that the turn-level unified diff has changed. Contains the latest aggregated diff across all file changes in the turn."""
    model_config = ConfigDict(extra="allow")

    diff: str
    threadId: str
    turnId: str

class TurnError(BaseModel):
    model_config = ConfigDict(extra="allow")

    additionalDetails: str | None = None
    codexErrorInfo: CodexErrorInfo | None = None
    message: str

class TurnPlanStep(BaseModel):
    model_config = ConfigDict(extra="allow")

    status: TurnPlanStepStatus
    step: str

class TurnPlanUpdatedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    explanation: str | None = None
    plan: list[TurnPlanStep]
    threadId: str
    turnId: str

class TurnStartedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    threadId: str
    turn: Turn

class WindowsSandboxSetupCompletedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    error: str | None = None
    mode: WindowsSandboxSetupMode
    success: bool

class WindowsWorldWritableWarningNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    extraCount: int
    failedScan: bool
    samplePaths: list[str]

class HttpConnectionFailedCodexErrorInfo(BaseModel):
    model_config = ConfigDict(extra="forbid")

    httpConnectionFailed: HttpConnectionFailedCodexErrorInfoHttpConnectionFailed

class ResponseStreamConnectionFailedCodexErrorInfo(BaseModel):
    """Failed to connect to the response SSE stream."""
    model_config = ConfigDict(extra="forbid")

    responseStreamConnectionFailed: ResponseStreamConnectionFailedCodexErrorInfoResponseStreamConnectionFailed

class ResponseStreamDisconnectedCodexErrorInfo(BaseModel):
    """The response SSE stream disconnected in the middle of a turn before completion."""
    model_config = ConfigDict(extra="forbid")

    responseStreamDisconnected: ResponseStreamDisconnectedCodexErrorInfoResponseStreamDisconnected

class ResponseTooManyFailedAttemptsCodexErrorInfo(BaseModel):
    """Reached the retry limit for responses."""
    model_config = ConfigDict(extra="forbid")

    responseTooManyFailedAttempts: ResponseTooManyFailedAttemptsCodexErrorInfoResponseTooManyFailedAttempts

class ActiveTurnNotSteerableCodexErrorInfo(BaseModel):
    """Returned when `turn/start` or `turn/steer` is submitted while the current active turn cannot accept same-turn steering, for example `/review` or manual `/compact`."""
    model_config = ConfigDict(extra="forbid")

    activeTurnNotSteerable: ActiveTurnNotSteerableCodexErrorInfoActiveTurnNotSteerable

class ReadCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    name: str
    path: str
    type: Literal["read"]

class ListFilesCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    path: str | None = None
    type: Literal["listFiles"]

class SearchCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    path: str | None = None
    query: str | None = None
    type: Literal["search"]

class UnknownCommandAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    command: str
    type: Literal["unknown"]

class InputTextDynamicToolCallOutputContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    type: Literal["inputText"]

class InputImageDynamicToolCallOutputContentItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    imageUrl: str
    type: Literal["inputImage"]

class AddPatchChangeKind(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["add"]

class DeletePatchChangeKind(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["delete"]

class UpdatePatchChangeKind(BaseModel):
    model_config = ConfigDict(extra="allow")

    move_path: str | None = None
    type: Literal["update"]

class CustomSessionSource(BaseModel):
    model_config = ConfigDict(extra="forbid")

    custom: str

class SubAgentSessionSource(BaseModel):
    model_config = ConfigDict(extra="forbid")

    subAgent: SubAgentSource

class ThreadSpawnSubAgentSource(BaseModel):
    model_config = ConfigDict(extra="forbid")

    thread_spawn: ThreadSpawnSubAgentSourceThreadSpawn

class OtherSubAgentSource(BaseModel):
    model_config = ConfigDict(extra="forbid")

    other: str

class UserMessageThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    content: list[UserInput]
    id: str
    type: Literal["userMessage"]

class HookPromptThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    fragments: list[HookPromptFragment]
    id: str
    type: Literal["hookPrompt"]

class AgentMessageThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    memoryCitation: MemoryCitation | None = None
    phase: MessagePhase | None = None
    text: str
    type: Literal["agentMessage"]

class PlanThreadItem(BaseModel):
    """EXPERIMENTAL - proposed plan item content. The completed plan item is authoritative and may not match the concatenation of `PlanDelta` text."""
    model_config = ConfigDict(extra="allow")

    id: str
    text: str
    type: Literal["plan"]

class ReasoningThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    content: list[str] = []
    id: str
    summary: list[str] = []
    type: Literal["reasoning"]

class CommandExecutionThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    aggregatedOutput: str | None = None
    command: str
    commandActions: list[CommandAction]
    cwd: str
    durationMs: int | None = None
    exitCode: int | None = None
    id: str
    processId: str | None = None
    source: CommandExecutionSource = "agent"
    status: CommandExecutionStatus
    type: Literal["commandExecution"]

class FileChangeThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    changes: list[FileUpdateChange]
    id: str
    status: PatchApplyStatus
    type: Literal["fileChange"]

class McpToolCallThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    arguments: Any
    durationMs: int | None = None
    error: McpToolCallError | None = None
    id: str
    result: McpToolCallResult | None = None
    server: str
    status: McpToolCallStatus
    tool: str
    type: Literal["mcpToolCall"]

class DynamicToolCallThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    arguments: Any
    contentItems: list[Any] | None = None
    durationMs: int | None = None
    id: str
    status: DynamicToolCallStatus
    success: bool | None = None
    tool: str
    type: Literal["dynamicToolCall"]

class CollabAgentToolCallThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    agentsStates: dict[str, CollabAgentState]
    id: str
    model: str | None = None
    prompt: str | None = None
    reasoningEffort: ReasoningEffort | None = None
    receiverThreadIds: list[str]
    senderThreadId: str
    status: CollabAgentToolCallStatus
    tool: CollabAgentTool
    type: Literal["collabAgentToolCall"]

class WebSearchThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    action: WebSearchAction | None = None
    id: str
    query: str
    type: Literal["webSearch"]

class ImageViewThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    path: str
    type: Literal["imageView"]

class ImageGenerationThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    result: str
    revisedPrompt: str | None = None
    savedPath: str | None = None
    status: str
    type: Literal["imageGeneration"]

class EnteredReviewModeThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    review: str
    type: Literal["enteredReviewMode"]

class ExitedReviewModeThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    review: str
    type: Literal["exitedReviewMode"]

class ContextCompactionThreadItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    id: str
    type: Literal["contextCompaction"]

class NotLoadedThreadStatus(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["notLoaded"]

class IdleThreadStatus(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["idle"]

class SystemErrorThreadStatus(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["systemError"]

class ActiveThreadStatus(BaseModel):
    model_config = ConfigDict(extra="allow")

    activeFlags: list[ThreadActiveFlag]
    type: Literal["active"]

class TextUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    text: str
    text_elements: list[TextElement] = []
    type: Literal["text"]

class ImageUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["image"]
    url: str

class LocalImageUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    path: str
    type: Literal["localImage"]

class SkillUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    path: str
    type: Literal["skill"]

class MentionUserInput(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    path: str
    type: Literal["mention"]

class SearchWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    queries: list[Any] | None = None
    query: str | None = None
    type: Literal["search"]

class OpenPageWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["openPage"]
    url: str | None = None

class FindInPageWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    pattern: str | None = None
    type: Literal["findInPage"]
    url: str | None = None

class OtherWebSearchAction(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: Literal["other"]

class ErrorNotification2(BaseModel):
    """NEW NOTIFICATIONS"""
    model_config = ConfigDict(extra="allow")

    method: Literal["error"]
    params: ErrorNotification

class ThreadStartedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["thread/started"]
    params: ThreadStartedNotification

class ThreadStatusChangedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["thread/status/changed"]
    params: ThreadStatusChangedNotification

class ThreadArchivedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["thread/archived"]
    params: ThreadArchivedNotification

class ThreadUnarchivedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["thread/unarchived"]
    params: ThreadUnarchivedNotification

class ThreadClosedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["thread/closed"]
    params: ThreadClosedNotification

class SkillsChangedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["skills/changed"]
    params: SkillsChangedNotification

class ThreadNameUpdatedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["thread/name/updated"]
    params: ThreadNameUpdatedNotification

class ThreadTokenUsageUpdatedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["thread/tokenUsage/updated"]
    params: ThreadTokenUsageUpdatedNotification

class TurnStartedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["turn/started"]
    params: TurnStartedNotification

class HookStartedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["hook/started"]
    params: HookStartedNotification

class TurnCompletedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["turn/completed"]
    params: TurnCompletedNotification

class HookCompletedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["hook/completed"]
    params: HookCompletedNotification

class TurnDiffUpdatedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["turn/diff/updated"]
    params: TurnDiffUpdatedNotification

class TurnPlanUpdatedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["turn/plan/updated"]
    params: TurnPlanUpdatedNotification

class ItemStartedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["item/started"]
    params: ItemStartedNotification

class ItemAutoApprovalReviewStartedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["item/autoApprovalReview/started"]
    params: ItemGuardianApprovalReviewStartedNotification

class ItemAutoApprovalReviewCompletedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["item/autoApprovalReview/completed"]
    params: ItemGuardianApprovalReviewCompletedNotification

class ItemCompletedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["item/completed"]
    params: ItemCompletedNotification

class ItemAgentMessageDeltaNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["item/agentMessage/delta"]
    params: AgentMessageDeltaNotification

class ItemPlanDeltaNotification(BaseModel):
    """EXPERIMENTAL - proposed plan streaming deltas for plan items."""
    model_config = ConfigDict(extra="allow")

    method: Literal["item/plan/delta"]
    params: PlanDeltaNotification

class CommandExecOutputDeltaNotification2(BaseModel):
    """Stream base64-encoded stdout/stderr chunks for a running `command/exec` session."""
    model_config = ConfigDict(extra="allow")

    method: Literal["command/exec/outputDelta"]
    params: CommandExecOutputDeltaNotification

class ItemCommandExecutionOutputDeltaNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["item/commandExecution/outputDelta"]
    params: CommandExecutionOutputDeltaNotification

class ItemCommandExecutionTerminalInteractionNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["item/commandExecution/terminalInteraction"]
    params: TerminalInteractionNotification

class ItemFileChangeOutputDeltaNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["item/fileChange/outputDelta"]
    params: FileChangeOutputDeltaNotification

class ServerRequestResolvedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["serverRequest/resolved"]
    params: ServerRequestResolvedNotification

class ItemMcpToolCallProgressNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["item/mcpToolCall/progress"]
    params: McpToolCallProgressNotification

class McpServerOauthLoginCompletedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["mcpServer/oauthLogin/completed"]
    params: McpServerOauthLoginCompletedNotification

class McpServerStartupStatusUpdatedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["mcpServer/startupStatus/updated"]
    params: McpServerStatusUpdatedNotification

class AccountUpdatedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["account/updated"]
    params: AccountUpdatedNotification

class AccountRateLimitsUpdatedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["account/rateLimits/updated"]
    params: AccountRateLimitsUpdatedNotification

class AppListUpdatedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["app/list/updated"]
    params: AppListUpdatedNotification

class FsChangedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["fs/changed"]
    params: FsChangedNotification

class ItemReasoningSummaryTextDeltaNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["item/reasoning/summaryTextDelta"]
    params: ReasoningSummaryTextDeltaNotification

class ItemReasoningSummaryPartAddedNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["item/reasoning/summaryPartAdded"]
    params: ReasoningSummaryPartAddedNotification

class ItemReasoningTextDeltaNotification(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["item/reasoning/textDelta"]
    params: ReasoningTextDeltaNotification

class ThreadCompactedNotification(BaseModel):
    """Deprecated: Use `ContextCompaction` item type instead."""
    model_config = ConfigDict(extra="allow")

    method: Literal["thread/compacted"]
    params: ContextCompactedNotification

class ModelReroutedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["model/rerouted"]
    params: ModelReroutedNotification

class DeprecationNoticeNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["deprecationNotice"]
    params: DeprecationNoticeNotification

class ConfigWarningNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["configWarning"]
    params: ConfigWarningNotification

class FuzzyFileSearchSessionUpdatedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["fuzzyFileSearch/sessionUpdated"]
    params: FuzzyFileSearchSessionUpdatedNotification

class FuzzyFileSearchSessionCompletedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["fuzzyFileSearch/sessionCompleted"]
    params: FuzzyFileSearchSessionCompletedNotification

class ThreadRealtimeStartedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["thread/realtime/started"]
    params: ThreadRealtimeStartedNotification

class ThreadRealtimeItemAddedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["thread/realtime/itemAdded"]
    params: ThreadRealtimeItemAddedNotification

class ThreadRealtimeTranscriptUpdatedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["thread/realtime/transcriptUpdated"]
    params: ThreadRealtimeTranscriptUpdatedNotification

class ThreadRealtimeOutputAudioDeltaNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["thread/realtime/outputAudio/delta"]
    params: ThreadRealtimeOutputAudioDeltaNotification

class ThreadRealtimeErrorNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["thread/realtime/error"]
    params: ThreadRealtimeErrorNotification

class ThreadRealtimeClosedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["thread/realtime/closed"]
    params: ThreadRealtimeClosedNotification

class WindowsWorldWritableWarningNotification2(BaseModel):
    """Notifies the user of world-writable directories on Windows, which cannot be protected by the sandbox."""
    model_config = ConfigDict(extra="allow")

    method: Literal["windows/worldWritableWarning"]
    params: WindowsWorldWritableWarningNotification

class WindowsSandboxSetupCompletedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["windowsSandbox/setupCompleted"]
    params: WindowsSandboxSetupCompletedNotification

class AccountLoginCompletedNotification2(BaseModel):
    model_config = ConfigDict(extra="allow")

    method: Literal["account/login/completed"]
    params: AccountLoginCompletedNotification

class HttpConnectionFailedCodexErrorInfoHttpConnectionFailed(BaseModel):
    model_config = ConfigDict(extra="allow")

    httpStatusCode: int | None = None

class ResponseStreamConnectionFailedCodexErrorInfoResponseStreamConnectionFailed(BaseModel):
    model_config = ConfigDict(extra="allow")

    httpStatusCode: int | None = None

class ResponseStreamDisconnectedCodexErrorInfoResponseStreamDisconnected(BaseModel):
    model_config = ConfigDict(extra="allow")

    httpStatusCode: int | None = None

class ResponseTooManyFailedAttemptsCodexErrorInfoResponseTooManyFailedAttempts(BaseModel):
    model_config = ConfigDict(extra="allow")

    httpStatusCode: int | None = None

class ActiveTurnNotSteerableCodexErrorInfoActiveTurnNotSteerable(BaseModel):
    model_config = ConfigDict(extra="allow")

    turnKind: NonSteerableTurnKind

class ThreadSpawnSubAgentSourceThreadSpawn(BaseModel):
    model_config = ConfigDict(extra="allow")

    agent_nickname: str | None = None
    agent_path: AgentPath | None = None
    agent_role: str | None = None
    depth: int
    parent_thread_id: ThreadId

AbsolutePathBuf: TypeAlias = str

AgentPath: TypeAlias = str

AuthMode: TypeAlias = Literal["apikey", "chatgpt", "chatgptAuthTokens"]

CodexErrorInfo: TypeAlias = Literal["contextWindowExceeded", "usageLimitExceeded", "serverOverloaded", "internalServerError", "unauthorized", "badRequest", "threadRollbackFailed", "sandboxError", "other"] | HttpConnectionFailedCodexErrorInfo | ResponseStreamConnectionFailedCodexErrorInfo | ResponseStreamDisconnectedCodexErrorInfo | ResponseTooManyFailedAttemptsCodexErrorInfo | ActiveTurnNotSteerableCodexErrorInfo

CollabAgentStatus: TypeAlias = Literal["pendingInit", "running", "interrupted", "completed", "errored", "shutdown", "notFound"]

CollabAgentTool: TypeAlias = Literal["spawnAgent", "sendInput", "resumeAgent", "wait", "closeAgent"]

CollabAgentToolCallStatus: TypeAlias = Literal["inProgress", "completed", "failed"]

CommandAction: TypeAlias = ReadCommandAction | ListFilesCommandAction | SearchCommandAction | UnknownCommandAction

CommandExecOutputStream: TypeAlias = Literal["stdout", "stderr"]

CommandExecutionSource: TypeAlias = Literal["agent", "userShell", "unifiedExecStartup", "unifiedExecInteraction"]

CommandExecutionStatus: TypeAlias = Literal["inProgress", "completed", "failed", "declined"]

DynamicToolCallOutputContentItem: TypeAlias = InputTextDynamicToolCallOutputContentItem | InputImageDynamicToolCallOutputContentItem

DynamicToolCallStatus: TypeAlias = Literal["inProgress", "completed", "failed"]

FuzzyFileSearchMatchType: TypeAlias = Literal["file", "directory"]

GuardianApprovalReviewStatus: TypeAlias = Literal["inProgress", "approved", "denied", "aborted"]

GuardianRiskLevel: TypeAlias = Literal["low", "medium", "high"]

HookEventName: TypeAlias = Literal["preToolUse", "postToolUse", "sessionStart", "userPromptSubmit", "stop"]

HookExecutionMode: TypeAlias = Literal["sync", "async"]

HookHandlerType: TypeAlias = Literal["command", "prompt", "agent"]

HookOutputEntryKind: TypeAlias = Literal["warning", "stop", "feedback", "context", "error"]

HookRunStatus: TypeAlias = Literal["running", "completed", "failed", "blocked", "stopped"]

HookScope: TypeAlias = Literal["thread", "turn"]

McpServerStartupState: TypeAlias = Literal["starting", "ready", "failed", "cancelled"]

McpToolCallStatus: TypeAlias = Literal["inProgress", "completed", "failed"]

MessagePhase: TypeAlias = Literal["commentary", "final_answer"]

ModelRerouteReason: TypeAlias = Literal["highRiskCyberActivity"]

NonSteerableTurnKind: TypeAlias = Literal["review", "compact"]

PatchApplyStatus: TypeAlias = Literal["inProgress", "completed", "failed", "declined"]

PatchChangeKind: TypeAlias = AddPatchChangeKind | DeletePatchChangeKind | UpdatePatchChangeKind

PlanType: TypeAlias = Literal["free", "go", "plus", "pro", "team", "self_serve_business_usage_based", "business", "enterprise_cbp_usage_based", "enterprise", "edu", "unknown"]

RealtimeConversationVersion: TypeAlias = Literal["v1", "v2"]

ReasoningEffort: TypeAlias = Literal["none", "minimal", "low", "medium", "high", "xhigh"]

RequestId: TypeAlias = str | int

SessionSource: TypeAlias = Literal["cli", "vscode", "exec", "appServer", "unknown"] | CustomSessionSource | SubAgentSessionSource

SkillsChangedNotification: TypeAlias = dict[str, Any]

SubAgentSource: TypeAlias = Literal["review", "compact", "memory_consolidation"] | ThreadSpawnSubAgentSource | OtherSubAgentSource

ThreadActiveFlag: TypeAlias = Literal["waitingOnApproval", "waitingOnUserInput"]

ThreadId: TypeAlias = str

ThreadItem: TypeAlias = UserMessageThreadItem | HookPromptThreadItem | AgentMessageThreadItem | PlanThreadItem | ReasoningThreadItem | CommandExecutionThreadItem | FileChangeThreadItem | McpToolCallThreadItem | DynamicToolCallThreadItem | CollabAgentToolCallThreadItem | WebSearchThreadItem | ImageViewThreadItem | ImageGenerationThreadItem | EnteredReviewModeThreadItem | ExitedReviewModeThreadItem | ContextCompactionThreadItem

ThreadStatus: TypeAlias = NotLoadedThreadStatus | IdleThreadStatus | SystemErrorThreadStatus | ActiveThreadStatus

TurnPlanStepStatus: TypeAlias = Literal["pending", "inProgress", "completed"]

TurnStatus: TypeAlias = Literal["completed", "interrupted", "failed", "inProgress"]

UserInput: TypeAlias = TextUserInput | ImageUserInput | LocalImageUserInput | SkillUserInput | MentionUserInput

WebSearchAction: TypeAlias = SearchWebSearchAction | OpenPageWebSearchAction | FindInPageWebSearchAction | OtherWebSearchAction

WindowsSandboxSetupMode: TypeAlias = Literal["elevated", "unelevated"]

ServerNotification: TypeAlias = ErrorNotification2 | ThreadStartedNotification2 | ThreadStatusChangedNotification2 | ThreadArchivedNotification2 | ThreadUnarchivedNotification2 | ThreadClosedNotification2 | SkillsChangedNotification2 | ThreadNameUpdatedNotification2 | ThreadTokenUsageUpdatedNotification2 | TurnStartedNotification2 | HookStartedNotification2 | TurnCompletedNotification2 | HookCompletedNotification2 | TurnDiffUpdatedNotification2 | TurnPlanUpdatedNotification2 | ItemStartedNotification2 | ItemAutoApprovalReviewStartedNotification | ItemAutoApprovalReviewCompletedNotification | ItemCompletedNotification2 | ItemAgentMessageDeltaNotification | ItemPlanDeltaNotification | CommandExecOutputDeltaNotification2 | ItemCommandExecutionOutputDeltaNotification | ItemCommandExecutionTerminalInteractionNotification | ItemFileChangeOutputDeltaNotification | ServerRequestResolvedNotification2 | ItemMcpToolCallProgressNotification | McpServerOauthLoginCompletedNotification2 | McpServerStartupStatusUpdatedNotification | AccountUpdatedNotification2 | AccountRateLimitsUpdatedNotification2 | AppListUpdatedNotification2 | FsChangedNotification2 | ItemReasoningSummaryTextDeltaNotification | ItemReasoningSummaryPartAddedNotification | ItemReasoningTextDeltaNotification | ThreadCompactedNotification | ModelReroutedNotification2 | DeprecationNoticeNotification2 | ConfigWarningNotification2 | FuzzyFileSearchSessionUpdatedNotification2 | FuzzyFileSearchSessionCompletedNotification2 | ThreadRealtimeStartedNotification2 | ThreadRealtimeItemAddedNotification2 | ThreadRealtimeTranscriptUpdatedNotification2 | ThreadRealtimeOutputAudioDeltaNotification2 | ThreadRealtimeErrorNotification2 | ThreadRealtimeClosedNotification2 | WindowsWorldWritableWarningNotification2 | WindowsSandboxSetupCompletedNotification2 | AccountLoginCompletedNotification2
