# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict


class ToolRequestUserInputOption(BaseModel):
    """EXPERIMENTAL. Defines a single selectable option for request_user_input."""
    model_config = ConfigDict(extra="allow")

    description: str
    label: str

class ToolRequestUserInputQuestion(BaseModel):
    """EXPERIMENTAL. Represents one request_user_input question and its required options."""
    model_config = ConfigDict(extra="allow")

    header: str
    id: str
    isOther: bool = False
    isSecret: bool = False
    options: list[Any] | None = None
    question: str

class ToolRequestUserInputParams(BaseModel):
    """EXPERIMENTAL. Params sent with a request_user_input event."""
    model_config = ConfigDict(extra="allow")

    itemId: str
    questions: list[ToolRequestUserInputQuestion]
    threadId: str
    turnId: str
