# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict


class ClientInfo(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    title: str | None = None
    version: str

class InitializeCapabilities(BaseModel):
    """Client-declared capabilities negotiated during initialize."""
    model_config = ConfigDict(extra="allow")

    experimentalApi: bool = False
    optOutNotificationMethods: list[Any] | None = None

class InitializeParams(BaseModel):
    model_config = ConfigDict(extra="allow")

    capabilities: InitializeCapabilities | None = None
    clientInfo: ClientInfo
