#!/usr/bin/env python3
# pyright: reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false
# ruff: noqa: ANN401, C901, E501, PLR0911, PLR0912, PLR2004, S603
#
# ANN401: JSON schema parsing is inherently dynamic here.
# C901/PLR0912: JSON Schema dispatch naturally produces complex, branchy generator methods.
# E501: Generated-code templates and schema docstrings are long by nature.
# PLR0911: Type rendering uses early returns per schema construct.
# PLR2004: Small template-shaping constants are clearer inline here.
# S603: We intentionally invoke the local codex CLI.

from __future__ import annotations

import argparse
import json
import keyword
import re
import shutil
import subprocess
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
RAW_SCHEMA_DIR = REPO_ROOT / ".codex_schemas"
OUTPUT_DIR = REPO_ROOT / "src/assistant/codex/schemas"
ROOT_SCHEMA_FILENAME = "codex_app_server_protocol.schemas.json"
CODEX_COMMAND = (
    "codex",
    "app-server",
    "generate-json-schema",
    "--out",
    str(RAW_SCHEMA_DIR),
)

HEADER = """# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
# pyright: reportAssignmentType=false
# ruff: noqa: E501, N815, RUF100
#
# E501: Generated schema unions and descriptions are long.
# N815: Generated models preserve schema field casing.
# RUF100: Keep generated file-level Ruff suppressions stable across files.
"""
ROOT_INIT = """# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
"""

PACKAGE_INIT = """# Generated by scripts/generate_codex_schemas.py. DO NOT EDIT.
"""

JsonObject = dict[str, Any]


@dataclass(frozen=True, slots=True)
class SchemaFile:
    schema_path: Path
    output_path: Path
    module_parts: tuple[str, ...]
    type_name: str
    schema: JsonObject


@dataclass(slots=True)
class TypeRef:
    expr: str
    deps: set[str] = field(default_factory=set)


@dataclass(slots=True)
class FieldSpec:
    python_name: str
    schema_name: str
    annotation: str
    required: bool
    default_repr: str | None


@dataclass(slots=True)
class DefinitionSpec:
    name: str
    kind: str
    body_lines: list[str]
    alias_deps: set[str] = field(default_factory=set)


class ModuleRenderer:
    def __init__(
        self,
        *,
        schema_file: SchemaFile,
        schema_files: dict[Path, SchemaFile],
    ) -> None:
        self._schema_file = schema_file
        self._schema_files = schema_files
        self._module_root = OUTPUT_DIR
        self._definitions: dict[str, JsonObject] = {}
        self._definition_order: list[str] = []
        self._definition_names_by_ref: dict[str, str] = {}
        self._rendered: dict[str, DefinitionSpec] = {}
        self._external_imports: dict[str, set[str]] = defaultdict(set)
        self._needs_any = False
        self._needs_base_model = False
        self._needs_config_dict = False
        self._needs_field = False
        self._needs_literal = False
        self._needs_type_alias = False

    def render_module(self) -> str:
        schema = self._schema_file.schema
        definitions = schema.get("definitions", {})
        self._register_definitions(definitions=definitions)

        root_name = self._schema_file.type_name
        root_schema = dict(schema)
        root_schema.pop("$schema", None)
        root_schema.pop("definitions", None)
        self._register_definition(root_name, root_schema)
        self._render_all_definitions()

        lines = [
            HEADER.rstrip(),
            "from __future__ import annotations",
            "",
        ]
        typing_imports = []
        if self._needs_any:
            typing_imports.append("Any")
        if self._needs_literal:
            typing_imports.append("Literal")
        if self._needs_type_alias:
            typing_imports.append("TypeAlias")
        if typing_imports:
            lines.append(f"from typing import {', '.join(sorted(typing_imports))}")

        pydantic_imports = []
        if self._needs_base_model:
            pydantic_imports.append("BaseModel")
        if self._needs_config_dict:
            pydantic_imports.append("ConfigDict")
        if self._needs_field:
            pydantic_imports.append("Field")
        if pydantic_imports:
            lines.append(f"from pydantic import {', '.join(sorted(pydantic_imports))}")

        for module_name in sorted(self._external_imports):
            names = ", ".join(sorted(self._external_imports[module_name]))
            lines.append(f"from {module_name} import {names}")

        if len(lines) > 3:
            lines.append("")

        helper_names = [name for name in self._definition_order if name != root_name]
        for name in helper_names:
            spec = self._rendered[name]
            lines.extend(spec.body_lines)
            lines.append("")

        root_spec = self._rendered[root_name]
        lines.extend(root_spec.body_lines)
        lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def _register_definition(self, name: str, schema: JsonObject) -> None:
        if name in self._definitions:
            return
        self._definitions[name] = schema
        self._definition_order.append(name)

    def _register_definitions(
        self,
        *,
        definitions: JsonObject,
        prefix: tuple[str, ...] = (),
    ) -> None:
        for definition_name, definition_schema in definitions.items():
            if not isinstance(definition_schema, dict):
                continue

            definition_path = (*prefix, definition_name)
            if _looks_like_schema_definition(definition_schema):
                python_name = _to_type_name(" ".join(definition_path))
                self._definition_names_by_ref["/".join(definition_path)] = python_name
                self._register_definition(python_name, definition_schema)
                continue

            self._register_definitions(
                definitions=definition_schema,
                prefix=definition_path,
            )

    def _register_inline_definition(self, name_hint: str, schema: JsonObject) -> str:
        candidate = _to_type_name(name_hint)
        if not candidate:
            candidate = "AnonymousSchema"

        name = candidate
        index = 2
        while name in self._definitions:
            name = f"{candidate}{index}"
            index += 1

        self._register_definition(name, schema)
        return name

    def _render_all_definitions(self) -> None:
        queue = list(self._definition_order)
        while queue:
            name = queue.pop(0)
            if name in self._rendered:
                continue

            spec = self._render_named_definition(name=name, schema=self._definitions[name])
            self._rendered[name] = spec

            for queued_name in self._definition_order:
                if queued_name not in self._rendered and queued_name not in queue:
                    queue.append(queued_name)

        alias_names = {
            name for name, spec in self._rendered.items() if spec.kind == "alias"
        }
        helper_names = [name for name in self._definition_order if name != self._schema_file.type_name]
        root_name = self._schema_file.type_name
        ordered_helpers = self._sort_aliases_after_classes(helper_names, alias_names)
        self._definition_order = [*ordered_helpers, root_name]

    def _sort_aliases_after_classes(
        self,
        names: list[str],
        alias_names: set[str],
    ) -> list[str]:
        class_names = [name for name in names if name not in alias_names]
        alias_graph = {
            name: {
                dep
                for dep in self._rendered[name].alias_deps
                if dep in alias_names and dep in names and dep != name
            }
            for name in names
            if name in alias_names
        }

        alias_order: list[str] = []
        visiting: set[str] = set()
        visited: set[str] = set()

        def visit(name: str) -> None:
            if name in visited or name not in alias_graph:
                return
            if name in visiting:
                return
            visiting.add(name)
            for dependency in sorted(alias_graph[name]):
                visit(dependency)
            visiting.remove(name)
            visited.add(name)
            alias_order.append(name)

        for alias_name in sorted(alias_graph):
            visit(alias_name)

        return [*class_names, *alias_order]

    def _render_named_definition(self, *, name: str, schema: JsonObject) -> DefinitionSpec:
        if _is_object_model(schema):
            return self._render_class_definition(name=name, schema=schema)
        return self._render_alias_definition(name=name, schema=schema)

    def _render_class_definition(self, *, name: str, schema: JsonObject) -> DefinitionSpec:
        self._needs_base_model = True
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        fields: list[FieldSpec] = []
        used_field_names: set[str] = set()

        for field_name, field_schema in properties.items():
            python_name = _to_field_name(field_name)
            python_name = _dedupe_field_name(python_name, used_field_names)

            default_value = (
                field_schema.get("default")
                if isinstance(field_schema, dict)
                else None
            )
            field_type = self._render_type(
                field_schema,
                context_name=f"{name}{_to_type_name(field_name)}",
            )

            annotation = field_type.expr
            default_repr: str | None
            is_required = field_name in required

            if default_value is not None:
                default_repr = repr(default_value)
            elif not is_required:
                if "None" not in annotation:
                    annotation = f"{annotation} | None"
                default_repr = "None"
            else:
                default_repr = None

            fields.append(
                FieldSpec(
                    python_name=python_name,
                    schema_name=field_name,
                    annotation=annotation,
                    required=is_required,
                    default_repr=default_repr,
                )
            )

        extra_mode = _get_extra_mode(schema)
        lines = [f"class {name}(BaseModel):"]
        if schema.get("description"):
            lines.append(f'    """{_clean_docstring(schema["description"])}"""')

        self._needs_config_dict = True
        lines.append(f'    model_config = ConfigDict(extra="{extra_mode}")')
        lines.append("")

        if not fields:
            lines.append("    pass")
            return DefinitionSpec(name=name, kind="class", body_lines=lines)

        for field_spec in fields:
            if field_spec.schema_name != field_spec.python_name:
                self._needs_field = True
                if field_spec.default_repr is None:
                    assignment = f' = Field(alias="{field_spec.schema_name}")'
                else:
                    assignment = (
                        f' = Field(default={field_spec.default_repr}, '
                        f'alias="{field_spec.schema_name}")'
                    )
            elif field_spec.default_repr is not None:
                assignment = f" = {field_spec.default_repr}"
            else:
                assignment = ""

            lines.append(
                f"    {field_spec.python_name}: {field_spec.annotation}{assignment}"
            )

        return DefinitionSpec(name=name, kind="class", body_lines=lines)

    def _render_alias_definition(self, *, name: str, schema: JsonObject) -> DefinitionSpec:
        type_ref = self._render_type(schema, context_name=name)
        self._needs_type_alias = True
        return DefinitionSpec(
            name=name,
            kind="alias",
            body_lines=[f"{name}: TypeAlias = {type_ref.expr}"],
            alias_deps=type_ref.deps,
        )

    def _render_type(self, schema: Any, *, context_name: str) -> TypeRef:
        if schema is True:
            self._needs_any = True
            return TypeRef("Any")

        if schema is False:
            self._needs_any = True
            return TypeRef("Any")

        if not isinstance(schema, dict):
            self._needs_any = True
            return TypeRef("Any")

        if "$ref" in schema:
            return self._render_ref(schema["$ref"])

        if "enum" in schema:
            self._needs_literal = True
            literal_values = ", ".join(repr(value) for value in schema["enum"])
            return TypeRef(f"Literal[{literal_values}]")

        if "const" in schema:
            self._needs_literal = True
            return TypeRef(f"Literal[{schema['const']!r}]")

        if "allOf" in schema:
            rendered_types = [
                self._render_type(item, context_name=context_name)
                for item in schema["allOf"]
            ]
            if len(rendered_types) == 1:
                return rendered_types[0]
            return self._render_union(rendered_types)

        if "anyOf" in schema:
            return self._render_union(
                [
                    self._render_type(item, context_name=context_name)
                    for item in schema["anyOf"]
                ]
            )

        if "oneOf" in schema:
            return self._render_union(
                [
                    self._render_type(item, context_name=context_name)
                    for item in schema["oneOf"]
                ]
            )

        schema_type = schema.get("type")
        if isinstance(schema_type, list):
            return self._render_union(
                [
                    self._render_type({"type": item}, context_name=context_name)
                    for item in schema_type
                ]
            )

        if schema_type == "object":
            properties = schema.get("properties", {})
            additional_properties = schema.get("additionalProperties")
            if properties:
                inline_name = schema.get("title") or context_name
                python_name = self._register_inline_definition(
                    inline_name,
                    {
                        key: value
                        for key, value in schema.items()
                        if key != "title"
                    },
                )
                return TypeRef(python_name, deps={python_name})

            if isinstance(additional_properties, dict):
                value_type = self._render_type(
                    additional_properties,
                    context_name=f"{context_name}Value",
                )
                return TypeRef(
                    f"dict[str, {value_type.expr}]",
                    deps=set(value_type.deps),
                )

            self._needs_any = True
            return TypeRef("dict[str, Any]")

        if schema_type == "array":
            items = self._render_type(
                schema.get("items", True),
                context_name=f"{context_name}Item",
            )
            return TypeRef(f"list[{items.expr}]", deps=set(items.deps))

        if schema_type == "string":
            return TypeRef("str")
        if schema_type == "integer":
            return TypeRef("int")
        if schema_type == "number":
            return TypeRef("float")
        if schema_type == "boolean":
            return TypeRef("bool")
        if schema_type == "null":
            return TypeRef("None")

        self._needs_any = True
        return TypeRef("Any")

    def _render_union(self, rendered_types: list[TypeRef]) -> TypeRef:
        expressions: list[str] = []
        deps: set[str] = set()
        for rendered_type in rendered_types:
            if rendered_type.expr in expressions:
                deps.update(rendered_type.deps)
                continue
            expressions.append(rendered_type.expr)
            deps.update(rendered_type.deps)

        if not expressions:
            self._needs_any = True
            return TypeRef("Any")
        if len(expressions) == 1:
            return TypeRef(expressions[0], deps)

        return TypeRef(" | ".join(expressions), deps)

    def _render_ref(self, ref: str) -> TypeRef:
        if ref.startswith("#/definitions/"):
            ref_path = ref.removeprefix("#/definitions/")
            name = self._definition_names_by_ref.get(ref_path)
            if name is None:
                name = _to_type_name(ref_path)
            return TypeRef(name, deps={name})

        path_text, _, _fragment = ref.partition("#")
        target_path = (self._schema_file.schema_path.parent / path_text).resolve()
        relative_path = target_path.relative_to(RAW_SCHEMA_DIR.resolve())
        target = self._schema_files[relative_path]
        module_name = self._relative_import(target.module_parts)
        self._external_imports[module_name].add(target.type_name)
        return TypeRef(target.type_name)

    def _relative_import(self, target_parts: tuple[str, ...]) -> str:
        current_package = self._schema_file.module_parts[:-1]
        target_package = target_parts[:-1]
        target_module = target_parts[-1]

        common_length = 0
        for current_part, target_part in zip(
            current_package,
            target_package,
            strict=True,
        ):
            if current_part != target_part:
                break
            common_length += 1

        up_levels = len(current_package) - common_length
        prefix = "." * (up_levels + 1)
        suffix_parts = (*target_package[common_length:], target_module)
        suffix = ".".join(suffix_parts)
        if not suffix:
            return prefix
        return f"{prefix}{suffix}"


def _is_object_model(schema: JsonObject) -> bool:
    if schema.get("type") != "object":
        return False
    return bool(schema.get("properties"))


def _get_extra_mode(schema: JsonObject) -> str:
    additional_properties = schema.get("additionalProperties")
    if additional_properties is False:
        return "forbid"
    return "allow"


def _clean_docstring(value: str) -> str:
    return value.replace('"""', r"\"\"\"")


def _to_type_name(value: str) -> str:
    if not value:
        return "UnnamedSchema"

    parts = re.findall(r"[A-Z]+(?=[A-Z][a-z]|\d|$)|[A-Z]?[a-z]+|\d+", value)
    if not parts:
        parts = re.split(r"[^0-9A-Za-z]+", value)
    normalized = "".join(part.capitalize() for part in parts if part)
    if not normalized:
        normalized = "UnnamedSchema"
    if normalized[0].isdigit():
        normalized = f"Schema{normalized}"
    return normalized


def _to_module_name(value: str) -> str:
    snake = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    snake = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", snake)
    snake = re.sub(r"[^0-9A-Za-z]+", "_", snake).strip("_").lower()
    if not snake:
        snake = "schema"
    if snake[0].isdigit():
        snake = f"schema_{snake}"
    return snake


def _to_field_name(value: str) -> str:
    field_name = re.sub(r"[^0-9A-Za-z_]+", "_", value).strip("_")
    if not field_name:
        field_name = "field"
    if field_name[0].isdigit():
        field_name = f"field_{field_name}"
    if keyword.iskeyword(field_name):
        field_name = f"{field_name}_"
    if field_name == "schema":
        field_name = f"{field_name}_"
    return field_name


def _dedupe_field_name(value: str, used_field_names: set[str]) -> str:
    field_name = value
    index = 2
    while field_name in used_field_names:
        field_name = f"{value}_{index}"
        index += 1
    used_field_names.add(field_name)
    return field_name


def _looks_like_schema_definition(value: JsonObject) -> bool:
    schema_keys = {
        "$ref",
        "additionalProperties",
        "allOf",
        "anyOf",
        "const",
        "enum",
        "items",
        "oneOf",
        "properties",
        "required",
        "title",
        "type",
    }
    return any(key in value for key in schema_keys)


def _discover_schema_files(schema_root: Path) -> dict[Path, SchemaFile]:
    schema_files: dict[Path, SchemaFile] = {}
    schema_path = schema_root / ROOT_SCHEMA_FILENAME
    if not schema_path.exists():
        msg = f"Missing root schema: {schema_path}"
        raise FileNotFoundError(msg)

    relative_path = schema_path.relative_to(schema_root)
    schema = json.loads(schema_path.read_text())
    type_name = _to_type_name(schema.get("title", schema_path.stem))
    module_parts = tuple(_to_module_name(part) for part in relative_path.with_suffix("").parts)
    output_path = OUTPUT_DIR.joinpath(*module_parts).with_suffix(".py")
    schema_files[relative_path] = SchemaFile(
        schema_path=schema_path,
        output_path=output_path,
        module_parts=module_parts,
        type_name=type_name,
        schema=schema,
    )
    return schema_files


def _write_output_tree(schema_files: dict[Path, SchemaFile]) -> None:
    if OUTPUT_DIR.exists():
        shutil.rmtree(OUTPUT_DIR)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    (OUTPUT_DIR / "__init__.py").write_text(ROOT_INIT)

    package_dirs = {OUTPUT_DIR}
    for schema_file in schema_files.values():
        package_dirs.update(
            parent
            for parent in schema_file.output_path.parents
            if OUTPUT_DIR in parent.parents or parent == OUTPUT_DIR
        )

    for package_dir in sorted(package_dirs):
        if package_dir == OUTPUT_DIR:
            continue
        package_dir.mkdir(parents=True, exist_ok=True)
        init_path = package_dir / "__init__.py"
        if not init_path.exists():
            init_path.write_text(PACKAGE_INIT)

    for schema_file in schema_files.values():
        renderer = ModuleRenderer(schema_file=schema_file, schema_files=schema_files)
        schema_file.output_path.parent.mkdir(parents=True, exist_ok=True)
        schema_file.output_path.write_text(renderer.render_module())


def _refresh_raw_schemas() -> None:
    if RAW_SCHEMA_DIR.exists():
        shutil.rmtree(RAW_SCHEMA_DIR)

    subprocess.run(
        CODEX_COMMAND,
        check=True,
        cwd=REPO_ROOT,
    )


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--skip-refresh",
        action="store_true",
        help="Use existing .codex_schemas instead of regenerating from codex app-server.",
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    if not args.skip_refresh:
        _refresh_raw_schemas()

    schema_files = _discover_schema_files(RAW_SCHEMA_DIR)
    _write_output_tree(schema_files)


if __name__ == "__main__":
    main()
